color: null
fieldLayouts:
  79b7369f-d6ff-4ebd-9281-1fe745aa4f8c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-04-29T15:33:05+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 39335836-758b-432e-a4a9-b2f3c1707697
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-29T15:35:26+00:00'
            elementCondition: null
            fieldUid: d99528c4-136b-413c-9799-56fd20edd2c6 # Headline
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7bf9895d-ce5f-409b-a38c-daf407490eb6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-29T15:35:26+00:00'
            elementCondition: null
            fieldUid: ad1324f8-1337-475f-8516-ab1e13543027 # Intro
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1b91f7c7-0072-4ee7-b787-db342d05dea1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-29T15:35:26+00:00'
            elementCondition: null
            fieldUid: f1944b34-730a-4bbe-8a1b-33fe56c07107 # Secondary text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1f8b1dd0-2044-4a0c-9f78-b5d4122df1fb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-29T15:35:26+00:00'
            elementCondition: null
            fieldUid: eb089684-4134-4cd9-a60d-4aaac63db8f4 # Link
            handle: null
            includeInCards: false
            instructions: null
            label: 'Application Link'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0945b825-997c-4aad-a0f3-3c9fb84b690c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-29T15:35:26+00:00'
            elementCondition: null
            fieldUid: 62e3c2ea-24fd-42e2-a9ba-3602f1d6e2e8 # Header Background
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c981a5d0-3b79-4b8b-a7b9-219b71366ec1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-29T15:35:26+00:00'
            elementCondition: null
            fieldUid: 33c3763c-9f38-4c39-bebd-48bbec68e094 # Header Alignment
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cb54e08d-8047-463e-b225-30b3b99c6861
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-29T15:49:40+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 9d52652c-9456-4b87-8888-f4df64bacc3e
            userCondition: null
          -
            dateAdded: '2025-04-29T15:49:40+00:00'
            elementCondition: null
            fieldUid: d99528c4-136b-413c-9799-56fd20edd2c6 # Headline
            handle: generalInfoHeadline
            includeInCards: false
            instructions: 'Defaults to "General Info"'
            label: 'General Info Headline'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 43257cbf-de88-4e5c-85a2-e31cb4dc0bae
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-29T15:58:39+00:00'
            elementCondition: null
            heading: 'Application Phase'
            type: craft\fieldlayoutelements\Heading
            uid: a3c53d5a-6f78-45c2-94f5-6ec164941522
            userCondition: null
          -
            dateAdded: '2025-04-29T15:51:32+00:00'
            elementCondition: null
            fieldUid: abb2edcb-afed-4766-9c25-594bf7d42262 # Date
            handle: applicationDateStart
            includeInCards: false
            instructions: null
            label: 'Application Date (Start)'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7cc455ba-6b3b-4afe-9c4f-220999910bde
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-04-29T15:53:34+00:00'
            elementCondition: null
            fieldUid: abb2edcb-afed-4766-9c25-594bf7d42262 # Date
            handle: applicationDateEnd
            includeInCards: false
            instructions: null
            label: 'Application Date (End)'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9027a720-a01b-438e-ab13-5f803e3f1445
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-04-29T15:56:27+00:00'
            elementCondition: null
            fieldUid: abb2edcb-afed-4766-9c25-594bf7d42262 # Date
            handle: selectionPhaseStart
            includeInCards: false
            instructions: null
            label: 'Selection Phase (Start)'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 67403530-faa9-4b1c-82f9-cb9e99f70e3a
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-04-29T15:56:27+00:00'
            elementCondition: null
            fieldUid: abb2edcb-afed-4766-9c25-594bf7d42262 # Date
            handle: selectionPhaseEnd
            includeInCards: false
            instructions: null
            label: 'Selection Phase (End)'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bc0ded4a-b573-4d91-89db-f14ef1d79183
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-04-29T15:59:14+00:00'
            elementCondition: null
            heading: Funding
            type: craft\fieldlayoutelements\Heading
            uid: 35422782-c24d-4e16-9167-340b11315551
            userCondition: null
          -
            dateAdded: '2025-04-29T16:00:41+00:00'
            elementCondition: null
            fieldUid: abb2edcb-afed-4766-9c25-594bf7d42262 # Date
            handle: initialFundingStart
            includeInCards: false
            instructions: null
            label: 'Initial Funding (Start)'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b0e12bef-6ed6-4e56-8cc4-78bddea86502
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-04-29T16:00:41+00:00'
            elementCondition: null
            fieldUid: abb2edcb-afed-4766-9c25-594bf7d42262 # Date
            handle: initialFundingEnd
            includeInCards: false
            instructions: null
            label: 'Initial Funding (End)'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 606b4154-5aa6-4dd3-bfbe-0231a38e3d1c
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-04-29T16:03:55+00:00'
            elementCondition: null
            fieldUid: 8a2262ef-cde3-425f-a9a4-4f531b781c31 # Amount
            handle: initialFundingAmount
            includeInCards: false
            instructions: null
            label: 'Initial Funding Amount'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f123d821-cd78-45ed-b29d-7d47b69ed57b
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-04-29T16:03:55+00:00'
            elementCondition: null
            heading: 'Second Stage Funding'
            type: craft\fieldlayoutelements\Heading
            uid: 61951077-a4ad-4f09-a29d-28b49888ede8
            userCondition: null
          -
            dateAdded: '2025-04-29T16:03:55+00:00'
            elementCondition: null
            fieldUid: abb2edcb-afed-4766-9c25-594bf7d42262 # Date
            handle: secondStageFundingStart
            includeInCards: false
            instructions: null
            label: 'Second Stage Funding (Start)'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 557725d6-7d80-4089-96a6-0b20ee235d1a
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-04-29T16:03:55+00:00'
            elementCondition: null
            fieldUid: abb2edcb-afed-4766-9c25-594bf7d42262 # Date
            handle: secondStageFundingEnd
            includeInCards: false
            instructions: null
            label: 'Second Stage Funding (End)'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 22053f9a-b885-418a-b16a-c58cc02bc137
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-04-29T16:03:55+00:00'
            elementCondition: null
            fieldUid: 8a2262ef-cde3-425f-a9a4-4f531b781c31 # Amount
            handle: secondStageFundingAmount
            includeInCards: false
            instructions: null
            label: 'Second Stage Funding Amount'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a4886fef-e27c-4c8d-9746-54f4e0dc1fd8
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-04-29T23:02:29+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 3bf08059-1661-40db-8a25-25301b7c510f
            userCondition: null
          -
            dateAdded: '2025-04-29T23:06:54+00:00'
            elementCondition: null
            fieldUid: d99528c4-136b-413c-9799-56fd20edd2c6 # Headline
            handle: projectsWeFundHeadline
            includeInCards: false
            instructions: null
            label: 'Projects We Fund Headline'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 992248d8-4458-4d69-a186-500f16a0bbe5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-29T22:59:03+00:00'
            elementCondition: null
            fieldUid: 992e8da2-9620-4ec5-a2d5-2f8b3c2c23e6 # Application Text
            handle: projectsWeFundText
            includeInCards: false
            instructions: null
            label: 'Projects We Fund Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f32875cb-f1ce-4228-bbfa-eb893e26d816
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-29T23:08:42+00:00'
            elementCondition: null
            fieldUid: d99528c4-136b-413c-9799-56fd20edd2c6 # Headline
            handle: fundingCriteriaHeadline
            includeInCards: false
            instructions: null
            label: 'Funding Criteria Headline'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f7675a30-bdb6-46bb-b5cd-e3bc82c09ba2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-29T23:03:15+00:00'
            elementCondition: null
            fieldUid: 992e8da2-9620-4ec5-a2d5-2f8b3c2c23e6 # Application Text
            handle: fundingCriteriaText
            includeInCards: false
            instructions: null
            label: 'Funding Criteria Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6c7445b9-54b9-484b-83a8-439300618e89
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-29T15:35:26+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 66283519-b686-42d6-8fb8-6d47725b1019
            userCondition: null
          -
            dateAdded: '2025-04-29T15:35:26+00:00'
            elementCondition: null
            fieldUid: 1bf40018-82e4-4e44-bbd6-6f49c132678d # Modules
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9fb641b4-160b-46f9-b8b9-bca285e0b398
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 641ad115-9116-4554-a607-83973047b41b
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-29T15:35:26+00:00'
            elementCondition: null
            fieldUid: 0d857c68-7bb1-4ce7-b61f-671446aa8bb3 # SEO
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 884c439e-709b-4d65-9309-4bec5a24abaf
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 75d27a39-3e82-46eb-b0fc-7ebdfd9b315b
        userCondition: null
handle: application
hasTitleField: true
icon: null
name: Application
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
