color: null
fieldLayouts:
  1e6091d0-fce7-4a6f-84fd-9a05f8ebb92f:
    cardView:
      - 'layoutElement:fb7bf9c8-5781-4575-a811-352514751665'
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-19T09:40:13+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: fbbfbc82-6be8-4c62-9b55-db165fb41c1a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-07T08:20:25+00:00'
            elementCondition: null
            fieldUid: 0f8a3079-62db-4270-ac53-6903c9b28557 # Main Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 26239e62-4e84-4316-acc8-4b5b2ac939eb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-16T11:30:43+00:00'
            elementCondition: null
            fieldUid: ad1324f8-1337-475f-8516-ab1e13543027 # Intro
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8f9201e0-fa8d-4314-965b-6247968ad810
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-19T09:40:13+00:00'
            elementCondition: null
            fieldUid: 13a0aaca-3bd8-4653-b163-69738ce277c3 # Text
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fb7bf9c8-5781-4575-a811-352514751665
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-19T09:40:13+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: aed9da80-acf1-4ba4-8add-5819e0dae19c
            userCondition: null
          -
            dateAdded: '2025-04-07T17:37:58+00:00'
            elementCondition: null
            fieldUid: 2965e0c7-feb2-4aa2-98d4-de16d458eb30 # Categories
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 12fc11e1-20e7-4620-9c58-530ad4a03356
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-19T09:40:13+00:00'
            elementCondition: null
            fieldUid: 9c0f58c4-4b28-4aca-b80d-3b370bc38f9e # Next Reads
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ee84530e-bc02-4920-b19e-ea4e85144645
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-07T08:20:25+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: f99dcead-e6d0-4255-bb1b-59c13d3330f2
            userCondition: null
          -
            dateAdded: '2025-03-30T20:43:10+00:00'
            elementCondition: null
            fieldUid: cff97bfa-6eb7-473b-97c0-cc3af58c0f64 # Article ID
            handle: null
            includeInCards: false
            instructions: 'This only exists as a helper field for the data migration from the old site. Don’t change it.'
            label: 'Legacy Article ID'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8d630891-228e-4414-9a60-5ee77df7d111
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5d12f84b-5944-4af9-8531-1b53b56640bd
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-02-19T09:40:13+00:00'
            elementCondition: null
            fieldUid: 0d857c68-7bb1-4ce7-b61f-671446aa8bb3 # SEO
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ebafbf53-5680-488a-82da-c12bef60e42b
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: a6f20f01-439a-4b7f-b400-9dc40366a297
        userCondition: null
handle: article
hasTitleField: true
icon: memo
name: Article
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
