color: null
fieldLayouts:
  e80e6c57-cb9b-461d-b14c-add7b28f3e48:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-16T21:20:48+00:00'
            elementCondition: null
            fieldUid: d13f787b-b91b-4821-8104-46e509830347 # Avatar
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 15b958f9-a4d3-4882-800b-e2d2de380e28
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-04-16T21:11:09+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Name
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2253cfbb-2581-46e4-9289-0721429ef7fc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-16T21:15:02+00:00'
            elementCondition: null
            fieldUid: e30e243f-a8dc-43b7-b826-e4788906231f # Pronouns
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ce7adf0a-90f2-44fc-ab52-0c1ffbaa347a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-16T21:16:45+00:00'
            elementCondition: null
            fieldUid: 6848d2a0-5b5f-43f6-a0c7-22707ad5e028 # Bio
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3c70be4b-8f15-4562-b4f5-ab5dc71b5855
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0d6a4d08-efc8-4e50-8a8f-8fd29c5b0803
        userCondition: null
handle: author
hasTitleField: true
icon: null
name: Author
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
