color: null
fieldLayouts:
  533e0ca6-5a6f-43ba-aeeb-5922521c09ea:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-04-21T12:38:45+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Headline
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7e97f38c-f912-48cf-878f-bbdd38bdcd0c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-21T12:41:39+00:00'
            elementCondition: null
            fieldUid: 52ffa06e-5e33-4cd5-8821-d001532453b1 # Embed Code
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7643498b-ee5e-47d8-9e3b-2f977ed40266
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-21T12:41:39+00:00'
            elementCondition: null
            fieldUid: 183a1c32-7844-45ce-93f1-a991260eeadc # Caption
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9474a1a2-1109-4b07-8634-c72757385d28
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 502b7aa3-1802-4309-919c-b2135c4fb630
        userCondition: null
handle: embed
hasTitleField: true
icon: null
name: Embed
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
