color: null
fieldLayouts:
  5ce099ae-1fb1-4076-b4dd-6916f4401115:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-04-30T19:53:34+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Heading
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2234c8e9-66b1-4597-bdbd-05b1002710a3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-30T19:55:17+00:00'
            elementCondition: null
            fieldUid: 5f79b151-95c9-4cad-be78-175d28cb5d10 # Event Next Reads
            handle: null
            includeInCards: false
            instructions: null
            label: Teasers
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 920c7d4d-8028-4863-a278-c0f45fd06640
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 54efe15b-1c31-477f-a314-8bd6928a8209
        userCondition: null
handle: eventTeasers
hasTitleField: true
icon: null
name: 'Event Teasers'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
