color: null
fieldLayouts:
  0a6f96ff-f661-411f-9506-ff1f2df5e8f0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-04-03T10:13:34+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: 'Short Title'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0d06b633-f263-480c-9f72-547780195081
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-03T10:15:12+00:00'
            elementCondition: null
            fieldUid: eb089684-4134-4cd9-a60d-4aaac63db8f4 # External Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a0e27dfa-a3bb-48a1-8e4d-5238e6cabec1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 147003c3-525a-420c-9ae7-b84343bed30a
        userCondition: null
handle: externalPage
hasTitleField: true
icon: null
name: 'External Page'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
