color: null
fieldLayouts:
  5a2bd6cd-68b2-4616-aca3-756c78c3f933:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-03T10:15:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f7486108-7a41-4ff3-83e8-34c2b334e19f # Links
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 90c08698-7bd2-479b-885b-849ea0897a2e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3e01cea7-defb-4c3c-9545-52f873597eb3
        userCondition: null
handle: footerLinkGroup
hasTitleField: false
icon: null
name: 'Footer Link Group'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: none
