color: null
fieldLayouts:
  5814abf4-bd59-4f7c-bab9-9fe44aa69287:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-19T09:40:13+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: cc203093-39cb-4c07-9f5a-4fde053af5cf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-02T11:39:53+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: f0b54317-4f10-41b6-9f0f-56495cd412d1
            userCondition: null
          -
            dateAdded: '2025-05-02T11:39:53+00:00'
            elementCondition: null
            fieldUid: 1bf40018-82e4-4e44-bbd6-6f49c132678d # Modules
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 106e6058-b47c-47c3-95da-818b3d457fc1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7b70b50a-c718-421c-9f01-c898f00d7d4f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-02-19T09:40:13+00:00'
            elementCondition: null
            fieldUid: 0d857c68-7bb1-4ce7-b61f-671446aa8bb3 # SEO
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ce454fad-b946-4695-bb64-ef63434e1938
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 68e1e41a-cdb5-4605-8c4d-9213f222c621
        userCondition: null
handle: homepage
hasTitleField: true
icon: null
name: Homepage
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
