color: null
fieldLayouts:
  5600ec1a-2f71-4767-909e-adeffd45d915:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-04-03T10:11:35+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: 'Short Title'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ccae62a6-8e33-4c42-b84c-cdb5741689ef
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-03T10:14:31+00:00'
            elementCondition: null
            fieldUid: 59e53eb6-a51c-49ea-8d74-73c4434e20ef # Page
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8d0f3c5b-fd88-4bc5-a192-efe86711f4cd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 091c83a1-501c-4d4d-993b-678a3fd532aa
        userCondition: null
handle: internalPage
hasTitleField: true
icon: null
name: 'Internal Page'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
