color: null
fieldLayouts:
  119f7689-48c9-44a1-b181-a6a2248f4b62:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-23T08:37:05+00:00'
            elementCondition: null
            fieldUid: d13f787b-b91b-4821-8104-46e509830347 # Avatar
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7886ee19-1175-4868-baaa-9d69dc0cb823
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-04-23T08:33:55+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Name
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 840f55f5-3705-4a16-94a8-47f0f0d100a1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-23T08:37:05+00:00'
            elementCondition: null
            fieldUid: e30e243f-a8dc-43b7-b826-e4788906231f # Pronouns
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fe9512ee-b240-4aa6-ac41-8cd77274363b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-23T08:37:05+00:00'
            elementCondition: null
            fieldUid: 36d3151d-99ef-4672-9521-82f0e9b0646d # Role
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ffc585d3-6dd0-414c-885c-7f4115465b0b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-23T08:37:05+00:00'
            elementCondition: null
            fieldUid: 6848d2a0-5b5f-43f6-a0c7-22707ad5e028 # Bio
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 831d264f-f8b6-4414-99d1-d90fae7d16eb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-23T08:37:05+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 3cfe5b06-8b06-4f45-a7ea-191c1c713c50
            userCondition: null
          -
            dateAdded: '2025-04-23T08:37:05+00:00'
            elementCondition: null
            fieldUid: 7bb4d517-5179-42f5-a2b7-0400280d5411 # Website
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7291df43-3f41-445c-a275-631353344996
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-23T08:37:05+00:00'
            elementCondition: null
            fieldUid: 7601873a-7197-47a0-9e66-c07512a11dd2 # Email
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 430215a4-c6d2-4e76-a4b2-e0ea3916281c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-23T08:37:05+00:00'
            elementCondition: null
            fieldUid: f7486108-7a41-4ff3-83e8-34c2b334e19f # Links
            handle: null
            includeInCards: false
            instructions: null
            label: 'Additional Links'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e84d99e8-3e6e-4000-b487-62219e1d5976
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 87ababf1-7ffc-49b8-a946-cdf026ca4760
        userCondition: null
handle: juror
hasTitleField: true
icon: user
name: Juror
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
