color: null
fieldLayouts:
  4188e4b6-c204-4849-8455-8c1771422db9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-04-23T21:44:30+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Heading
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e97db3af-b257-4f5c-a1eb-a2ed86038ed3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-23T21:53:26+00:00'
            elementCondition: null
            fieldUid: f1c5c016-d5a6-471a-a030-91a4f9a88503 # Subheading
            handle: null
            includeInCards: false
            instructions: 'Optional subheading'
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ecc77a0d-999c-4b53-bb2e-f1b4b0780b15
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-04-23T21:53:26+00:00'
            elementCondition: null
            fieldUid: 02298633-6aff-40aa-9bf9-e8530102b352 # Date
            handle: null
            includeInCards: false
            instructions: 'Optional date'
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1adcc6fa-fdef-4043-ac6c-2b9ed2945754
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-04-23T21:53:26+00:00'
            elementCondition: null
            fieldUid: f4ddd6a2-288b-4881-a762-884e48b3f1f1 # Link List Text
            handle: null
            includeInCards: false
            instructions: null
            label: Text
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 10c9cc27-5bc5-45d7-b099-bccfceb15669
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-23T21:53:26+00:00'
            elementCondition: null
            fieldUid: eb089684-4134-4cd9-a60d-4aaac63db8f4 # Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bbdc9289-cb80-4ccf-966e-e78661c43cb7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3b79882b-2902-4a9b-86ee-ec7a8c1a49a8
        userCondition: null
handle: linkListRow
hasTitleField: true
icon: null
name: 'Link List Row'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
