color: null
fieldLayouts:
  891a0987-8507-48fc-a26a-abe43baf5697:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-04-23T21:32:44+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Heading
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7d7b40b5-3ca1-4d60-89b3-f70b6b3c74b0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-23T21:37:41+00:00'
            elementCondition: null
            fieldUid: f4ddd6a2-288b-4881-a762-884e48b3f1f1 # Link List Text
            handle: null
            includeInCards: false
            instructions: null
            label: Text
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d6b8ac55-9355-471a-866f-919a40a98768
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-23T21:53:48+00:00'
            elementCondition: null
            fieldUid: 1db838be-9fa8-4bea-9063-88e07757ad52 # Link List Links
            handle: null
            includeInCards: false
            instructions: null
            label: Links
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1afc76b8-ae21-4aab-8269-166478fc7f83
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3baa8b8b-cb0d-48da-bbbd-944b703792a9
        userCondition: null
handle: linkList
hasTitleField: true
icon: null
name: 'Link List'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
