color: null
fieldLayouts:
  5ecec522-16e2-4049-ac39-f20af6a8b057:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-03T21:15:13+00:00'
            elementCondition: null
            fieldUid: eb089684-4134-4cd9-a60d-4aaac63db8f4 # Link
            handle: null
            includeInCards: false
            instructions: null
            label: Link
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 50c759a5-075b-40f7-8a82-b426814dcc75
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 687ee6cc-9651-4630-a111-3158a4b3d235
        userCondition: null
handle: link
hasTitleField: false
icon: null
name: Link
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
