color: null
fieldLayouts:
  6105215e-3ab7-4d9c-be58-e68e0d6e2454:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-22T13:01:08+00:00'
            elementCondition: null
            fieldUid: 65bbee3d-0a45-412f-a8e5-04ee7c01d8af # People
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2305f06a-f49a-4291-ab43-0720fe2527de
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: aee623a3-d040-452b-9fd4-d45df491936b
        userCondition: null
handle: peopleGrid
hasTitleField: false
icon: null
name: 'People Grid'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
