color: null
fieldLayouts:
  a584bac7-632a-4656-aa19-a0a6b6def29a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-04-26T15:58:13+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6d084d7c-bcfb-4a81-b393-2a18734d34de
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-26T15:57:21+00:00'
            elementCondition: null
            fieldUid: a6825d2c-f661-4fd6-ac6e-b7b06cf823ab # Date(s)
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4b4ea8bc-0e9f-40e5-acc5-49f4cd6c44ce
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-28T08:26:21+00:00'
            elementCondition: null
            fieldUid: 747e573a-dea9-419c-9f81-e1778c7f1b13 # Phase Text
            handle: null
            includeInCards: false
            instructions: null
            label: Text
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c11b264a-8a8d-4944-a7c9-9ae0a9e4ae25
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7b246a66-657c-4836-9ddb-34694de32752
        userCondition: null
handle: phase
hasTitleField: true
icon: null
name: Phase
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
