color: null
fieldLayouts:
  9cf7fd69-1781-4313-acd5-5a2d016b24ce:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-03-30T19:35:37+00:00'
            elementCondition: null
            fieldUid: 276edf74-a032-4834-b9ef-5783f0b823d4 # Project ID
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b233697f-406c-4193-a93d-4e222afbe660
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-10T13:19:10+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: bc5ac3b3-512a-4ac8-8bbf-15fe8ebe22b5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-10T16:05:07+00:00'
            elementCondition: null
            fieldUid: 13a0aaca-3bd8-4653-b163-69738ce277c3 # Text
            handle: claim
            includeInCards: false
            instructions: null
            label: Claim
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9c056411-67d4-492f-9f86-e7a9854e8601
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-10T13:27:17+00:00'
            elementCondition: null
            fieldUid: 3bde5cb4-3323-4862-906f-40053b1122bc # Main Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f6d22296-a946-45b0-89f7-e675265acf40
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-10T13:37:53+00:00'
            elementCondition: null
            fieldUid: f4a87b3f-ed6d-49ce-8753-05dda85942a6 # Project Status
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d3ba407b-6545-4d06-be17-d106237c836c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-10T13:44:06+00:00'
            elementCondition: null
            fieldUid: 5a2c3e10-bf78-4986-aecd-f75829889851 # Project Topics
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7c757f76-4970-4108-bc6b-5141083d6b0a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-03T14:29:07+00:00'
            elementCondition: null
            fieldUid: c85b9b92-e92c-448e-be1b-853494683b99 # Project Technologies
            handle: projectTechnologies2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9f6ff707-4607-4c5c-8ed0-0bb77eeb6e8f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-03T14:30:50+00:00'
            elementCondition: null
            fieldUid: 860851bc-5058-4f0d-8f3f-481df7e56099 # Project Rounds
            handle: projectRounds2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5950d971-54fb-4823-bef5-ed344370a73e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-10T13:43:06+00:00'
            elementCondition: null
            fieldUid: f81e8821-286e-4e07-86f6-54880a45eafe # Project Team Members
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 644ce093-70e1-41fc-a874-bdd9913045c3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-10T13:39:21+00:00'
            elementCondition: null
            fieldUid: 67373325-a234-485a-a635-26dee1e7f325 # Project Links
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 84cff0f2-f938-46bc-bc9c-9630cb25792e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-10T13:27:17+00:00'
            elementCondition: null
            fieldUid: 13a0aaca-3bd8-4653-b163-69738ce277c3 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 60e77047-8443-4137-aa4f-f2ad68903de0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-03T14:29:07+00:00'
            elementCondition: null
            fieldUid: c85b9b92-e92c-448e-be1b-853494683b99 # Project Technologies
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d6cf108c-ba1b-47f5-919b-e5f8f8f55077
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-03T14:30:50+00:00'
            elementCondition: null
            fieldUid: 860851bc-5058-4f0d-8f3f-481df7e56099 # Project Rounds
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3ebd30bb-1ff9-483b-8f78-517eb120d5c8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8a52f532-1397-4933-b88f-1800076947c0
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-03-10T13:27:17+00:00'
            elementCondition: null
            fieldUid: 0d857c68-7bb1-4ce7-b61f-671446aa8bb3 # SEO
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b82ba2d5-8e6e-439f-a929-7c6e5b8ab443
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 9559918d-3bf1-40fd-b2a8-19edb232c3fb
        userCondition: null
handle: project
hasTitleField: true
icon: list-check
name: Project
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
