color: null
fieldLayouts:
  92f1f032-2ae3-47f0-bc5f-39bd85ec3d06:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-10T13:17:35+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a569f315-7313-4729-9e8d-014cf040c4e2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-09T13:38:45+00:00'
            elementCondition: null
            fieldUid: d99528c4-136b-413c-9799-56fd20edd2c6 # Headline
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f6ae81f5-b734-4cb4-9254-421a6bcc2a37
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-09T13:38:45+00:00'
            elementCondition: null
            fieldUid: ad1324f8-1337-475f-8516-ab1e13543027 # Intro
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c614197a-60b2-47a8-9e3c-4353bb4133e1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-09T13:38:45+00:00'
            elementCondition: null
            fieldUid: eb089684-4134-4cd9-a60d-4aaac63db8f4 # Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cbe86d61-2e1c-423f-9188-ad393b078828
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-09T13:38:45+00:00'
            elementCondition: null
            fieldUid: 62e3c2ea-24fd-42e2-a9ba-3602f1d6e2e8 # Header Background
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7f1349b3-deb8-4fc6-bce5-069b0bc12df1
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-04-14T20:53:37+00:00'
            elementCondition: null
            fieldUid: 33c3763c-9f38-4c39-bebd-48bbec68e094 # Header Alignment
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 13842ea0-7932-41f1-a72a-77c5a8531ec7
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-04-09T13:38:45+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 7aa25a2e-bb79-4641-b3e2-16236a2bfbdc
            userCondition: null
          -
            dateAdded: '2025-04-09T13:38:45+00:00'
            elementCondition: null
            fieldUid: 1bf40018-82e4-4e44-bbd6-6f49c132678d # Modules
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6d73c304-a46a-48c2-bcd0-efb3a2d47535
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7c4654da-4cec-43ca-bbac-5888861faf3e
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-03-10T13:19:14+00:00'
            elementCondition: null
            fieldUid: 0d857c68-7bb1-4ce7-b61f-671446aa8bb3 # SEO
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f73103fa-0e43-44d5-aad3-884cef26300f
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: ee658dbc-dd65-4edd-9995-85914058b4e5
        userCondition: null
handle: projectsIndex
hasTitleField: true
icon: null
name: 'Projects Index'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
