color: null
fieldLayouts:
  9cf7fd69-1781-4313-acd5-5a2d016b24ce:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-10T13:19:10+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: bc5ac3b3-512a-4ac8-8bbf-15fe8ebe22b5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-24T10:27:43+00:00'
            elementCondition: null
            fieldUid: d99528c4-136b-413c-9799-56fd20edd2c6 # Headline
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 615fef52-0841-4f37-8268-a14f76679b46
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-07T08:20:44+00:00'
            elementCondition: null
            fieldUid: 0f8a3079-62db-4270-ac53-6903c9b28557 # Main Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5b6fa2e7-ace4-466a-aaaf-536ab1d76aca
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-10T13:39:21+00:00'
            elementCondition: null
            fieldUid: 67373325-a234-485a-a635-26dee1e7f325 # Project Links
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 84cff0f2-f938-46bc-bc9c-9630cb25792e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-21T11:04:52+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 1f1cb804-c1fe-413d-acad-56b16f0d75b6
            userCondition: null
          -
            dateAdded: '2025-04-23T11:47:08+00:00'
            elementCondition: null
            fieldUid: f455cf70-e6e9-48c1-806f-753a2af85bea # Project Second Stage Funding
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c263ed50-7ff5-42c6-9025-ceb7ba46bd00
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-10T13:37:53+00:00'
            elementCondition: null
            fieldUid: f4a87b3f-ed6d-49ce-8753-05dda85942a6 # Project Status
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d3ba407b-6545-4d06-be17-d106237c836c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-10T13:43:06+00:00'
            elementCondition: null
            fieldUid: f81e8821-286e-4e07-86f6-54880a45eafe # Project Team Members
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 644ce093-70e1-41fc-a874-bdd9913045c3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-21T12:13:01+00:00'
            elementCondition: null
            fieldUid: 704f68f7-7b03-4825-a337-ab9d195a33e6 # Project License
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fbc9fc63-a39b-428d-8ce7-c4cab2d964cb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-21T12:16:07+00:00'
            elementCondition: null
            fieldUid: 5a633b8c-0848-4867-8990-245346e525e8 # Project Funding Amount
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dd4576ab-4e94-4943-885d-67c44a3be314
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-24T10:19:19+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 20bc7736-39fe-41b9-bb49-4982d62a07a8
            userCondition: null
          -
            dateAdded: '2025-04-03T14:30:50+00:00'
            elementCondition: null
            fieldUid: 860851bc-5058-4f0d-8f3f-481df7e56099 # Project Rounds
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3ebd30bb-1ff9-483b-8f78-517eb120d5c8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-10T13:44:06+00:00'
            elementCondition: null
            fieldUid: 5a2c3e10-bf78-4986-aecd-f75829889851 # Project Topics
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7c757f76-4970-4108-bc6b-5141083d6b0a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-03T14:29:07+00:00'
            elementCondition: null
            fieldUid: c85b9b92-e92c-448e-be1b-853494683b99 # Project Technologies
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d6cf108c-ba1b-47f5-919b-e5f8f8f55077
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-10T15:44:22+00:00'
            elementCondition: null
            fieldUid: 3d4c1a3f-6b2d-4919-a863-32877e6722ce # Project Year Groups
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d65f3f26-0095-4f84-9045-a3c488ece13c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-21T14:19:39+00:00'
            elementCondition: null
            fieldUid: 8c706102-ac71-4054-b178-d266051a8ba8 # Project Next Reads
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bceb9e20-1ab1-4f07-94be-033b5295293e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-18T14:23:11+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: a10e31a0-3684-4cad-ba51-dc595c737afa
            userCondition: null
          -
            dateAdded: '2025-03-10T13:27:17+00:00'
            elementCondition: null
            fieldUid: 13a0aaca-3bd8-4653-b163-69738ce277c3 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 60e77047-8443-4137-aa4f-f2ad68903de0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-21T11:04:52+00:00'
            elementCondition: null
            fieldUid: 1bf40018-82e4-4e44-bbd6-6f49c132678d # Modules
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1b9116e9-d487-42f3-9070-310f0bc2764c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-21T12:12:27+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 2d3ed17a-9c41-4cf9-864d-18e5e767ae5a
            userCondition: null
          -
            dateAdded: '2025-03-30T19:35:37+00:00'
            elementCondition: null
            fieldUid: 276edf74-a032-4834-b9ef-5783f0b823d4 # Project ID
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b233697f-406c-4193-a93d-4e222afbe660
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-10T16:05:07+00:00'
            elementCondition: null
            fieldUid: 13a0aaca-3bd8-4653-b163-69738ce277c3 # Text
            handle: claimOld
            includeInCards: false
            instructions: 'Will be deleted after import'
            label: 'Claim (Old)'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9c056411-67d4-492f-9f86-e7a9854e8601
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8a52f532-1397-4933-b88f-1800076947c0
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-03-10T13:27:17+00:00'
            elementCondition: null
            fieldUid: 0d857c68-7bb1-4ce7-b61f-671446aa8bb3 # SEO
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b82ba2d5-8e6e-439f-a929-7c6e5b8ab443
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 9559918d-3bf1-40fd-b2a8-19edb232c3fb
        userCondition: null
handle: project
hasTitleField: true
icon: list-check
name: Project
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
