color: null
fieldLayouts:
  d9147c00-4bee-46a5-aec5-ba65e88d2210:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-04-25T12:14:00+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: db5bc7d1-5ffd-41b7-954a-93ce6fe470f6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-25T12:21:54+00:00'
            elementCondition: null
            fieldUid: f7165950-84cb-4ae9-b955-b36db50e32e1 # Publication
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 02634f02-7885-409d-9db1-da2ce57b4fda
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-25T12:17:09+00:00'
            elementCondition: null
            fieldUid: 7eac1059-22fa-40a5-b327-b28832b8beb1 # Publication Cover
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c4633b32-fdd2-49ca-a61a-03061b005267
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-25T12:15:35+00:00'
            elementCondition: null
            fieldUid: f1c5c016-d5a6-471a-a030-91a4f9a88503 # Subheading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 30c8574f-d9cf-4ac2-bc82-068dc0896444
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: fdc4baaf-fb5a-4553-99cd-d24978a1da32
        userCondition: null
handle: publication
hasTitleField: true
icon: null
name: Publication
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
