color: null
fieldLayouts:
  77c312be-995e-4082-8b6a-5834636b90a0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-04-25T12:09:59+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Heading
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7d74c8a9-b57a-4f35-906c-745acf1e6a22
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-25T12:25:05+00:00'
            elementCondition: null
            fieldUid: f4ddd6a2-288b-4881-a762-884e48b3f1f1 # Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7b0f21fb-b28d-4f9e-9c64-0c63d5db84fe
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-25T12:24:08+00:00'
            elementCondition: null
            fieldUid: 734f959a-796d-4882-babd-df0495b02b2e # Publications
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9f2b20fd-9729-4a29-b157-30e79e2c81ce
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: afa81525-f356-4679-a96a-2a13951cf7cb
        userCondition: null
handle: relatedPublications
hasTitleField: true
icon: null
name: Publications
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
