color: null
fieldLayouts:
  76778b93-c3ca-4bf7-9817-10dac456f5cb:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-21T14:42:09+00:00'
            elementCondition: null
            fieldUid: 2d6b9ef4-4190-4cf7-9a92-b6f6b0fb7f61 # CTA Banner
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: adaddc40-3a24-405f-ba6e-8a732f9d5356
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 899f0267-e7eb-487c-9c3d-844993d190b0
        userCondition: null
handle: relatedCtaBanner
hasTitleField: false
icon: null
name: 'CTA Banner'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
