color: null
fieldLayouts:
  eca4346c-7870-462f-8403-845a9883a432:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-24T19:52:07+00:00'
            elementCondition: null
            fieldUid: d94ae721-befb-4d87-921e-3152926fdd9e # Step Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8cee48c5-b810-4be2-9104-034be7ad418b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b64ff3c6-8093-47b3-bff9-b5d6475524f9
        userCondition: null
handle: step
hasTitleField: false
icon: null
name: Step
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
