color: null
fieldLayouts:
  0a447b0b-b96a-4976-8ddf-4c29c0e18dfe:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-23T08:44:02+00:00'
            elementCondition: null
            fieldUid: d13f787b-b91b-4821-8104-46e509830347 # Avatar
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4abef0c6-4b31-42aa-a3e2-a22a13407884
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-04-23T08:40:23+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Name
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f2582ab0-9051-4652-a7fc-964a803c0a5c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-23T08:44:02+00:00'
            elementCondition: null
            fieldUid: e30e243f-a8dc-43b7-b826-e4788906231f # Pronouns
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f7032f14-1f81-46c6-bb4d-2603b07be69d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-23T08:44:02+00:00'
            elementCondition: null
            fieldUid: 36d3151d-99ef-4672-9521-82f0e9b0646d # Role
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a89d2535-fc91-4a76-a016-50cfe27b9f75
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-23T08:44:02+00:00'
            elementCondition: null
            fieldUid: 6848d2a0-5b5f-43f6-a0c7-22707ad5e028 # Bio
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d4ea75e5-e92b-4449-bbe9-84caffd45f5c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-23T08:44:02+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: b1b8334e-6956-476e-bf08-fd7cb342f5a3
            userCondition: null
          -
            dateAdded: '2025-04-23T08:44:02+00:00'
            elementCondition: null
            fieldUid: 7bb4d517-5179-42f5-a2b7-0400280d5411 # Website
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 044855fd-a53a-4352-b52b-48add3a42f0f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-23T08:44:02+00:00'
            elementCondition: null
            fieldUid: 7601873a-7197-47a0-9e66-c07512a11dd2 # Email
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: de7b011e-a57c-4d98-a3fa-f98cf44ac4c0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-23T08:44:02+00:00'
            elementCondition: null
            fieldUid: f7486108-7a41-4ff3-83e8-34c2b334e19f # Links
            handle: null
            includeInCards: false
            instructions: null
            label: 'Additional Links'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 45c7fa4f-7121-424d-8f11-f58df6c5101c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 75c17604-1de8-4682-b9b4-1230445be59e
        userCondition: null
handle: teamMember
hasTitleField: true
icon: null
name: 'Team Member'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
