color: null
fieldLayouts:
  5acc37d0-18d5-48ee-a9a1-6975d634b7d2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-04-23T10:46:22+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d90b9044-753f-4332-b459-2835ea9f8b64
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-23T10:49:12+00:00'
            elementCondition: null
            fieldUid: d99528c4-136b-413c-9799-56fd20edd2c6 # Headline
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ae7693e0-88a7-45ee-8370-4611d9b9ded9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-23T10:49:12+00:00'
            elementCondition: null
            fieldUid: ad1324f8-1337-475f-8516-ab1e13543027 # Intro
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2b4cdea5-26dd-4f4d-a0bc-6f969942cb0b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-29T15:09:13+00:00'
            elementCondition: null
            fieldUid: f1944b34-730a-4bbe-8a1b-33fe56c07107 # Secondary text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1bf50542-8b0b-41b2-8f8c-7d9c2a18ffe8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-23T10:49:12+00:00'
            elementCondition: null
            fieldUid: eb089684-4134-4cd9-a60d-4aaac63db8f4 # Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0aad5740-7161-4110-9deb-8453efe2fcf4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-23T10:49:12+00:00'
            elementCondition: null
            fieldUid: 62e3c2ea-24fd-42e2-a9ba-3602f1d6e2e8 # Header Background
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 10840ee8-327c-4e35-927e-cd725eb92487
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-23T10:49:12+00:00'
            elementCondition: null
            fieldUid: 33c3763c-9f38-4c39-bebd-48bbec68e094 # Header Alignment
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 19ac2588-cb8d-4804-97f4-519409a25130
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-23T10:49:12+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 1dbf2623-c004-434f-bded-8996327ca7d0
            userCondition: null
          -
            dateAdded: '2025-04-23T10:49:12+00:00'
            elementCondition: null
            fieldUid: 1bf40018-82e4-4e44-bbd6-6f49c132678d # Modules
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dbfafe00-936d-4e32-a377-9dcc09939e2f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2eda62d8-8651-4e54-aeca-53c9eccfff99
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-23T10:49:12+00:00'
            elementCondition: null
            fieldUid: 0d857c68-7bb1-4ce7-b61f-671446aa8bb3 # SEO
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f4c2bff9-3dff-4702-ab19-eba6263b0a7f
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: e4f8b498-4b65-4e69-91f0-13d36f8b43a0
        userCondition: null
handle: trendsIndex
hasTitleField: true
icon: null
name: 'Trends Index'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
