color: null
fieldLayouts:
  c8d90d98-c596-4de5-a53e-200e5b70e6b9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-04-23T11:00:00+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 33c8e813-b92c-4521-bdff-6e17921239f9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-23T11:02:03+00:00'
            elementCondition: null
            fieldUid: d99528c4-136b-413c-9799-56fd20edd2c6 # Headline
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d577dc9d-6850-49aa-9170-40e095cb9312
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-23T11:02:03+00:00'
            elementCondition: null
            fieldUid: 62e3c2ea-24fd-42e2-a9ba-3602f1d6e2e8 # Header Background
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6da67b9a-2203-4403-ae98-e363b147cb7a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-23T11:07:02+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: d6d65b2d-00a9-438b-94d3-6f6b14368c48
            userCondition: null
          -
            dateAdded: '2025-04-23T11:02:03+00:00'
            elementCondition: null
            fieldUid: ad1324f8-1337-475f-8516-ab1e13543027 # Intro
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 07a90aaf-188b-4f34-a763-8b047d3d1fcd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-23T11:07:02+00:00'
            elementCondition: null
            fieldUid: 13a0aaca-3bd8-4653-b163-69738ce277c3 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 39104e9b-6926-40b5-b242-790f1c9d6277
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-23T11:02:03+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 6170f56b-aff3-4226-991b-29d2a1c8db96
            userCondition: null
          -
            dateAdded: '2025-04-23T11:02:03+00:00'
            elementCondition: null
            fieldUid: 1bf40018-82e4-4e44-bbd6-6f49c132678d # Modules
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: deeb170b-847b-42b5-981f-3f4242cdfbd5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2e3e6142-938a-4754-bab3-255d7180926c
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-23T11:02:03+00:00'
            elementCondition: null
            fieldUid: 0d857c68-7bb1-4ce7-b61f-671446aa8bb3 # SEO
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8afdb306-228e-4379-a15d-e467c06ef054
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 69d1aafa-b333-4431-a966-f8584d1da423
        userCondition: null
handle: trend
hasTitleField: true
icon: null
name: Trend
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
