color: null
fieldLayouts:
  c6dbbeb0-a924-40a4-a144-138c327cf8c0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-12T21:20:13+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c58201ee-03b9-4996-a90e-b83fa4d01a28
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-12T21:22:44+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d99528c4-136b-413c-9799-56fd20edd2c6 # Headline
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 81d59d43-65d0-40e3-9715-f86f1a8f680d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-12T21:22:44+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ad1324f8-1337-475f-8516-ab1e13543027 # Intro
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 90cc5332-7c0e-4817-9e7e-5ab19b30facc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-12T21:22:44+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f1944b34-730a-4bbe-8a1b-33fe56c07107 # Secondary text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6e782cb3-84bf-47e5-af1e-fc5c033d54df
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-12T21:22:44+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: eb089684-4134-4cd9-a60d-4aaac63db8f4 # Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ddf8c7fa-de88-4b17-9dc8-a28f6285a37c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-12T21:22:44+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 62e3c2ea-24fd-42e2-a9ba-3602f1d6e2e8 # Header Background
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b1b9fa68-c3f2-4a3d-a660-dfee1726a278
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-12T21:22:44+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 33c3763c-9f38-4c39-bebd-48bbec68e094 # Header Alignment
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6c3582c7-8bb4-4563-81b8-21bdf12bcacd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-12T21:22:44+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 8d7e07cf-8ffc-45b6-8e79-7aefa0c41adf
            userCondition: null
          -
            dateAdded: '2025-05-12T21:22:44+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 1bf40018-82e4-4e44-bbd6-6f49c132678d # Modules
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b55bebf2-693b-4bb5-8e1f-a9416ee61c40
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d9a511e9-264e-4e7b-92de-80f24f8fde92
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-12T21:22:44+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0d857c68-7bb1-4ce7-b61f-671446aa8bb3 # SEO
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 471faff4-0355-4ee1-8aa5-895126ef9a85
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 6024f48e-03b1-4665-a707-fbc365ffc3fd
        userCondition: null
handle: yearGroupsIndex
hasTitleField: true
icon: null
name: 'Year Groups Index'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
