css: ".ck.ck-editor .button {\r\n  padding: 0.2em 0.4em;\r\n  background-color: grey;\r\n  color: white;\r\n  display: inline-block;\r\n}\r\n\r\n.ck.ck-editor .highlighted {\r\n  background-color: yellow;\r\n}"
headingLevels:
  - 2
  - 3
  - 4
  - 5
name: 'Standard (with Entry Types)'
options:
  list:
    properties:
      styles: false
  style:
    definitions:
      -
        classes:
          - button
        element: a
        name: Button
      -
        classes:
          - highlighted
        element: span
        name: Highlight
toolbar:
  - heading
  - style
  - '|'
  - bold
  - italic
  - strikethrough
  - link
  - bulletedList
  - numberedList
  - insertImage
  - '|'
  - createEntry
