css: ".ck.ck-editor .button {\r\n  padding: 0.2em 0.4em;\r\n  background-color: grey;\r\n  color: white;\r\n  display: inline-block;\r\n}"
headingLevels:
  - 2
  - 3
  - 4
  - 5
  - 6
listPlugin: ''
name: Standard
options:
  list:
    properties:
      styles: false
  style:
    definitions:
      -
        classes:
          - button
        element: a
        name: Button
toolbar:
  - sourceEditing
  - '|'
  - heading
  - style
  - '|'
  - blockQuote
  - bold
  - italic
  - strikethrough
  - link
  - bulletedList
  - numberedList
