headingLevels: false
name: Simple
options:
  link:
    decorators:
      openInNewTab:
        attributes:
          rel: 'noopener noreferrer'
          target: _blank
        label: 'Open in a new tab'
        mode: manual
  list:
    properties:
      styles: false
toolbar:
  - bold
  - italic
  - strikethrough
  - link
