defaultPlacement: end
fieldLayouts:
  87e8a030-a9c7-4e84-a095-fc835527b57b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-04-07T17:34:11+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 76f0f525-cd4f-4398-9588-584a9e9c6a27
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-07T17:45:57+00:00'
            elementCondition: null
            fieldUid: d99528c4-136b-413c-9799-56fd20edd2c6 # Headline
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3f4d7e8a-74a2-40c0-9dae-2b57f058a3ec
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-07T17:45:57+00:00'
            elementCondition: null
            fieldUid: ad1324f8-1337-475f-8516-ab1e13543027 # Intro
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 470733f7-369b-46b7-94d7-c54a2c5c5fd7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-07T17:47:09+00:00'
            elementCondition: null
            fieldUid: eb089684-4134-4cd9-a60d-4aaac63db8f4 # Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 27d0925b-6e0d-466b-bf83-1524d1be0fed
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-07T17:45:57+00:00'
            elementCondition: null
            fieldUid: 62e3c2ea-24fd-42e2-a9ba-3602f1d6e2e8 # Header Background
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c7ecca5b-e83b-4aa8-8073-2cad2d6e83d7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-08T18:09:43+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 29af61c2-e5b1-4afc-be67-2b037acb45be
            userCondition: null
          -
            dateAdded: '2025-04-08T18:09:43+00:00'
            elementCondition: null
            fieldUid: 1bf40018-82e4-4e44-bbd6-6f49c132678d # Modules
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7404d63c-ae2e-4724-90d8-4f52f400290c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 40d6167e-2173-4fa0-8cf5-d21f7b7e99b7
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-07T17:43:46+00:00'
            elementCondition: null
            fieldUid: 0d857c68-7bb1-4ce7-b61f-671446aa8bb3 # SEO
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 21312172-aa3f-4177-ae54-5c0596e5eb74
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: e0366936-04a1-43a4-a25c-96484d0601dc
        userCondition: null
handle: blogCategories
name: 'Blog Categories'
siteSettings:
  af0bbe1c-3613-4775-8a01-965b68d4e56e: # English
    hasUrls: true
    template: blog/_category.twig
    uriFormat: 'blog/{slug}'
  ddc3aedf-983b-4fa7-81eb-69fd761d71af: # German
    hasUrls: true
    template: blog/_category.twig
    uriFormat: 'blog/{slug}'
structure:
  maxLevels: null
  uid: 1fcfa357-e705-4720-8ccd-0f74378face9
