defaultPlacement: end
fieldLayouts:
  19db7c15-f464-44b3-8068-dc525e1d79a9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-04-10T15:39:05+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: a671a193-6bf0-4060-90d0-6016a628f600
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a619d16d-9386-49c8-90f7-52718226833f
        userCondition: null
handle: projectYearGroups
name: 'Project Year Groups'
siteSettings:
  af0bbe1c-3613-4775-8a01-965b68d4e56e: # English
    hasUrls: true
    template: project-year-groups/_category.twig
    uriFormat: 'project-year-groups/{slug}'
  ddc3aedf-983b-4fa7-81eb-69fd761d71af: # German
    hasUrls: true
    template: project-year-groups/_category.twig
    uriFormat: 'project-year-groups/{slug}'
structure:
  maxLevels: null
  uid: 13c66926-5fac-4096-a2f3-05efcfe40391
