defaultPlacement: end
fieldLayouts:
  cf313bd4-eec1-4407-baf6-3d62e85acfd7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-04-03T14:25:48+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: d8075789-0c7d-44bc-9a68-a2c8c2c11b4f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6c20f699-7c9b-4c83-9f80-335b25527ea0
        userCondition: null
handle: projectTechnologies
name: 'Project Technologies'
siteSettings:
  af0bbe1c-3613-4775-8a01-965b68d4e56e: # English
    hasUrls: true
    template: project-technologies/_category.twig
    uriFormat: 'project-technologies/{slug}'
  ddc3aedf-983b-4fa7-81eb-69fd761d71af: # German
    hasUrls: true
    template: project-technologies/_category.twig
    uriFormat: 'project-technologies/{slug}'
structure:
  maxLevels: 1
  uid: 3e288ef4-eb1d-428b-9577-909cb0cf7ec9
