defaultPlacement: end
fieldLayouts:
  6b1fffd6-5203-4079-bcaf-02047b791804:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-02T11:50:06+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 0dd9e51c-bded-4a1c-a165-30dfdd78e98d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-02T11:52:45+00:00'
            elementCondition: null
            fieldUid: d99528c4-136b-413c-9799-56fd20edd2c6 # Headline
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8731bbed-6c1c-4c24-a302-91c9b5cd0fa3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-02T11:52:45+00:00'
            elementCondition: null
            fieldUid: ad1324f8-1337-475f-8516-ab1e13543027 # Intro
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c1ac96de-0610-4557-a92c-e5fddce6a1b1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-02T11:52:45+00:00'
            elementCondition: null
            fieldUid: f1944b34-730a-4bbe-8a1b-33fe56c07107 # Secondary text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fabac1c4-969f-4465-9342-d8a6a8ecd412
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-02T11:52:45+00:00'
            elementCondition: null
            fieldUid: eb089684-4134-4cd9-a60d-4aaac63db8f4 # Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a7d6d819-7911-4161-ab6c-f5da67aab7cf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-02T11:52:45+00:00'
            elementCondition: null
            fieldUid: 62e3c2ea-24fd-42e2-a9ba-3602f1d6e2e8 # Header Background
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7372e9c8-655f-40f0-b149-40c7ea58b2a4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-02T11:52:45+00:00'
            elementCondition: null
            fieldUid: 33c3763c-9f38-4c39-bebd-48bbec68e094 # Header Alignment
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bf1ff291-0529-4956-8801-6d74f85daeeb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-02T11:52:45+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 3de5e911-e2e4-4ff1-8002-65c72d94a2aa
            userCondition: null
          -
            dateAdded: '2025-05-02T11:52:45+00:00'
            elementCondition: null
            fieldUid: 1bf40018-82e4-4e44-bbd6-6f49c132678d # Modules
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f02a73e3-9320-465c-a496-3349f87afc2a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e984823e-9791-43b9-8a56-657922469717
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-02T11:52:45+00:00'
            elementCondition: null
            fieldUid: 0d857c68-7bb1-4ce7-b61f-671446aa8bb3 # SEO
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4391ce78-67af-4720-ac60-5f1d0121cf06
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 24a76770-4997-42d5-a5d6-adda4b63a52a
        userCondition: null
handle: projectLicenses
name: 'Project Licenses'
siteSettings:
  af0bbe1c-3613-4775-8a01-965b68d4e56e: # English
    hasUrls: true
    template: projects/_category.twig
    uriFormat: 'projects/{slug}'
  ddc3aedf-983b-4fa7-81eb-69fd761d71af: # German
    hasUrls: true
    template: projects/_category.twig
    uriFormat: 'projects/{slug}'
structure:
  maxLevels: null
  uid: edaa33b0-1f8d-444f-bb41-4b564e2c97f4
