altTranslationKeyFormat: null
altTranslationMethod: site
fieldLayouts:
  1272fc47-fee0-4a8b-80d0-5c19ed9e14c6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-19T09:40:13+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: c61578a5-1e99-4edf-acec-42d50fc042c6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-07T08:17:29+00:00'
            elementCondition: null
            fieldUid: 183a1c32-7844-45ce-93f1-a991260eeadc # Caption
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8fbaeb9e-f5e6-4597-993d-573cf961e1bd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-12T16:17:51+00:00'
            elementCondition: null
            fieldUid: c670b800-a19f-4ca2-a056-283204e59d5d # Credit / License
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: addce637-1162-4b04-9b41-f84a4e16ffab
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-07T13:01:43+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 8568aee5-b9c2-428f-9927-d966235a4dce
            userCondition: null
          -
            dateAdded: '2025-04-07T13:01:43+00:00'
            elementCondition: null
            fieldUid: 6913623b-fb1d-419a-a6a4-270a7ec28d8b # Alt Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: 'Use this field for alt text for now, we’ll migrate to Craft’s native field (sits below) later.'
            type: craft\fieldlayoutelements\CustomField
            uid: 02e9a363-c534-4ab1-8d4d-635ad2824d98
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            dateAdded: '2025-04-07T13:09:45+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: e5c7bf55-0e4c-4711-825f-71e8109f9280
            userCondition: null
            warning: 'Don’t use this field yet'
            width: 100
        name: Content
        uid: b716d9f1-1e92-42c0-bf65-7e868c92a471
        userCondition: null
fs: uploadsFs
handle: uploads
name: Uploads
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: uploadsFs
transformSubpath: transforms
