columnSuffix: null
handle: applicationText
instructions: null
name: 'Application Text'
searchable: true
settings:
  advancedLinkFields: null
  availableTransforms: '*'
  availableVolumes: '*'
  characterLimit: null
  css: null
  cssFile: Standard-(with-Entry-Types).css
  defaultTransform: null
  defaultUploadLocationSubpath: null
  defaultUploadLocationVolume: null
  fullGraphqlData: false
  headingLevels:
    - '2'
    - '3'
    - '4'
    - '5'
  imageEntryTypeUid: null
  imageFieldUid: null
  imageMode: img
  js: null
  jsFile: Standard-(with-Entry-Types).json
  options: null
  parseEmbeds: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  toolbar:
    - heading
    - style
    - '|'
    - bold
    - italic
    - strikethrough
    - link
    - bulletedList
    - numberedList
    - insertImage
    - insertTable
    - '|'
  wordLimit: null
translationKeyFormat: null
translationMethod: site
type: craft\ckeditor\Field
