columnSuffix: null
handle: applicationText
instructions: null
name: 'Application Text'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  characterLimit: null
  css: ".ck.ck-editor .button {\r\n  padding: 0.2em 0.4em;\r\n  background-color: grey;\r\n  color: white;\r\n  display: inline-block;\r\n}\r\n\r\n.ck.ck-editor .highlighted {\r\n  background-color: yellow;\r\n}"
  cssFile: null
  defaultTransform: null
  fullGraphqlData: false
  headingLevels:
    - 2
    - 3
    - 4
    - 5
  js: null
  jsFile: null
  options:
    list:
      properties:
        styles: false
    style:
      definitions:
        -
          classes:
            - button
          element: a
          name: Button
        -
          classes:
            - highlighted
          element: span
          name: Highlight
  parseEmbeds: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  toolbar:
    - heading
    - style
    - '|'
    - bold
    - italic
    - strikethrough
    - link
    - bulletedList
    - numberedList
    - insertImage
    - '|'
  wordLimit: null
translationKeyFormat: null
translationMethod: site
type: craft\ckeditor\Field
