columnSuffix: null
handle: cards
instructions: null
name: Cards
searchable: true
settings:
  createButtonLabel: null
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - c84399c0-dd2f-498b-adbf-528b801843c4 # Card
        -
          - group
          - Allgemein
  includeTableView: false
  maxEntries: 4
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
