columnSuffix: null
handle: footerDescription
instructions: null
name: 'Footer Description'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  characterLimit: null
  css: null
  cssFile: null
  defaultTransform: null
  fullGraphqlData: false
  headingLevels: false
  js: null
  jsFile: Simple.json
  options: null
  parseEmbeds: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  toolbar:
    - bold
    - italic
    - strikethrough
    - link
  wordLimit: null
translationKeyFormat: null
translationMethod: site
type: craft\ckeditor\Field
