columnSuffix: null
handle: headerBackground
instructions: null
name: 'Header Background'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - 'Grey Background / Blue Pattern'
        -
          - value
          - greyBackgroundBluePattern
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'Grey Background / Dark Pink Pattern'
        -
          - value
          - greyBackgroundDarkPinkPattern
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Grey Background / Light Pink Pattern '
        -
          - value
          - greyBackgroundLightPinkPattern
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Light Blue Background / Dark Blue Pattern'
        -
          - value
          - lightBlueBackgroundDarkBluePattern
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Rich Blue Background / Dark Pink Pattern'
        -
          - value
          - richBlueBackgroundDarkPinkPattern
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Navy Blue Background / Light Blue Pattern'
        -
          - value
          - navyBlueBackgroundLightBluePattern
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\RadioButtons
