columnSuffix: null
handle: mainFooterLinks
instructions: null
name: 'Main Footer Links'
searchable: false
settings:
  createButtonLabel: 'Link Group'
  defaultIndexViewMode: cards
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 5bafc55c-8f31-4f9b-add0-49e9957e63a7 # Link Group
  includeTableView: false
  maxEntries: 3
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
