columnSuffix: null
handle: nextReads
instructions: 'Leave empty to always display the latest four articles automatically'
name: 'Next Reads'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  maintainHierarchy: false
  maxRelations: 4
  minRelations: null
  selectionLabel: 'Add entries as next reads'
  showCardsInGrid: false
  showSiteMenu: true
  sources:
    - 'section:375cd22a-99b6-4667-8ca6-caf2572459ed' # Blog
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
