columnSuffix: null
handle: projectRounds
instructions: null
name: 'Project Rounds'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showCardsInGrid: false
  showSiteMenu: false
  source: 'group:a06eff6a-35ff-45b1-9c02-c6ef2f3f948c' # Project Rounds
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Categories
