columnSuffix: null
handle: secondStage
instructions: null
name: 'Second Stage'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
