columnSuffix: null
handle: text
instructions: null
name: Text
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: 6fa1e10a-d063-4c10-a955-f1b3eda7e7ef # Standard (with Entry Types)
  createButtonLabel: null
  defaultTransform: null
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 62872793-9d0f-4ffe-a713-748f5c9c6605 # Charts
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: null
translationKeyFormat: null
translationMethod: site
type: craft\ckeditor\Field
