columnSuffix: null
handle: text
instructions: null
name: Text
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  characterLimit: null
  css: null
  cssFile: Standard-(with-Entry-Types).css
  defaultTransform: null
  entryTypes:
    -
      uid: 62872793-9d0f-4ffe-a713-748f5c9c6605 # Charts
    -
      uid: d26039c6-3f56-4e09-a666-c1fd8f160bee # Image Columns
  fullGraphqlData: false
  headingLevels:
    - 2
    - 3
    - 4
    - 5
  js: null
  jsFile: Standard-(with-Entry-Types).json
  options: null
  parseEmbeds: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  toolbar:
    - heading
    - style
    - '|'
    - bold
    - italic
    - strikethrough
    - link
    - bulletedList
    - numberedList
    - insertImage
    - '|'
    - createEntry
  wordLimit: null
translationKeyFormat: null
translationMethod: site
type: craft\ckeditor\Field
