columnSuffix: goyaurwq
handle: textEntryTypes
instructions: null
name: Text
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: '*'
  characterLimit: null
  css: null
  cssFile: Standard-(with-Entry-Types).css
  defaultTransform: null
  entryTypes:
    -
      uid: 894e5185-035a-41d1-b272-0b6c1608aabf # Side Heading + Text
    -
      uid: 824f9bd0-21d0-47fd-a48a-b8519da12b29 # Quote
    -
      uid: c08345c7-f10a-42ce-b893-7f2e82a46fbb # Embed
    -
      uid: 0a3f8849-b320-4a0e-929f-d5d0fddc7c45 # Gallery
  fullGraphqlData: false
  headingLevels:
    - 2
    - 3
    - 4
    - 5
  js: null
  jsFile: Standard-(with-Entry-Types).json
  options: null
  parseEmbeds: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: true
  sourceEditingGroups:
    - __ADMINS__
  toolbar:
    - heading
    - style
    - '|'
    - bold
    - italic
    - strikethrough
    - link
    - bulletedList
    - numberedList
    - insertImage
    - '|'
    - createEntry
  wordLimit: null
translationKeyFormat: null
translationMethod: site
type: craft\ckeditor\Field
