columnSuffix: null
handle: trackingBody
instructions: 'Add any tracking scripts to appear in the body of the page'
name: 'Tracking Body'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: true
  initialRows: 4
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
