dateModified: 1744904577
elementSources:
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: '*'
      tableAttributes:
        - section
        - postDate
        - expiryDate
        - link
      type: native
    -
      key: singles
      type: native
    -
      heading: Pages
      type: heading
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: 'section:375cd22a-99b6-4667-8ca6-caf2572459ed' # Blog
      tableAttributes:
        - postDate
        - expiryDate
        - link
      type: native
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: 'section:de820dbc-bd7e-4a0f-9554-3d750480d2a4' # Projects
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - authors
        - link
      type: native
    -
      key: 'section:6e040108-27cc-4a4a-bca9-c5e3ab1bdc04' # Generic Pages
      type: native
    -
      heading: People
      type: heading
    -
      key: 'section:a6babdad-fc37-48fb-ac86-088ea4129e1e' # Author
      type: native
email:
  fromEmail: $EMAIL_SYSTEM_ADDRESS
  fromName: $EMAIL_SENDER_NAME
  replyToEmail: null
  template: ''
  transportSettings:
    host: $EMAIL_SMTP_HOST
    password: $EMAIL_SMTP_PASS
    port: $EMAIL_SMTP_PORT
    useAuthentication: '1'
    username: $EMAIL_SMTP_USER
  transportType: craft\mail\transportadapters\Smtp
fs:
  uploadsFs:
    hasUrls: true
    name: 'Uploads FS'
    settings:
      path: '@webroot/uploads'
    type: craft\fs\Local
    url: '@web/uploads'
meta:
  __names__:
    0b9eb562-64e5-4b3c-9478-8cefd24e8039: Text # Text
    0d857c68-7bb1-4ce7-b61f-671446aa8bb3: SEO # SEO
    0f8a3079-62db-4270-ac53-6903c9b28557: 'Main Image' # Main Image
    1a0ed17a-7208-4b7e-894f-64506d5432d6: 'Events Index' # Events Index
    1bf40018-82e4-4e44-bbd6-6f49c132678d: Modules # Modules
    2b86894c-5b98-44d4-8ed6-88b2c8b5e601: 'Blog Index' # Blog Index
    3d4c1a3f-6b2d-4919-a863-32877e6722ce: 'Project Year Groups' # Project Year Groups
    4b6ba907-43f2-494b-9816-24894f8de0da: Newsletter # Newsletter
    4e97404d-0992-4280-b87e-903b4fc471c5: Navigation # Navigation
    5a2c3e10-bf78-4986-aecd-f75829889851: 'Project Topics' # Project Topics
    5bafc55c-8f31-4f9b-add0-49e9957e63a7: 'Footer Link Group' # Footer Link Group
    6c3461da-2d32-418a-803b-efe329a38c30: 'Article Author' # Article Author
    6ca70ace-9ae7-4dfa-a915-d1a24572619d: 'Footer Description' # Footer Description
    6e040108-27cc-4a4a-bca9-c5e3ab1bdc04: 'Generic Pages' # Generic Pages
    6fa1e10a-d063-4c10-a955-f1b3eda7e7ef: 'Standard (with Entry Types)' # Standard (with Entry Types)
    7e4dd8fe-6873-44a9-ada5-acf02698981d: 'Side Info' # Side Info
    7eb26dd5-1c10-45d1-a16b-85a148e4bf8a: 'Projects Index' # Projects Index
    8a18f61b-a93c-4302-8bde-b8f6ed6c0494: 'Inclusive Sans – Semibold' # Inclusive Sans – Semibold
    8d8e3436-a20e-4222-a530-d52fa736ae4d: 'Project Technologies' # Project Technologies
    9a1aea15-6b42-4b96-b047-ee412bfabc78: Intro # Intro
    9c0f58c4-4b28-4aca-b80d-3b370bc38f9e: 'Next Reads' # Next Reads
    13a0aaca-3bd8-4653-b163-69738ce277c3: Text # Text
    018c8387-bc84-4c1c-ae3a-186233bcf754: 'Secondary Footer Links' # Secondary Footer Links
    28f95d3d-986f-41ed-b23b-c2f3b747c2eb: Homepage # Homepage
    29d80674-cc17-4976-ad67-b3f611a07dc2: 'Events Index' # Events Index
    33c3763c-9f38-4c39-bebd-48bbec68e094: 'Header Alignment' # Header Alignment
    34dc108f-02bd-42cb-9481-0693c7bc32b4: 'Tracking Head' # Tracking Head
    58b0cfc4-a7f2-491d-a49a-a29faaacedf3: 'Inclusive Sans – Regular' # Inclusive Sans – Regular
    62e3c2ea-24fd-42e2-a9ba-3602f1d6e2e8: 'Header Background' # Header Background
    62efdaf8-a4e7-4149-bc72-3bd492681eba: 'Newsletter Side Title' # Newsletter Side Title
    69fb06a0-7361-46bd-a063-b293e6336a99: Description # Description
    72b63983-0825-4712-ab6f-b4d98ee4efd4: Standard # Standard
    91a7ad8a-d35b-4738-b71b-a18f899afc5d: 'Resize: width 2000px' # Resize: width 2000px
    98ac3e52-dafd-49ce-8852-a02e92879a39: 'Avatar (Small)' # Avatar (Small)
    137c86ac-e143-4792-b936-38c41302eccd: Fonts # Fonts
    183a1c32-7844-45ce-93f1-a991260eeadc: Caption # Caption
    276edf74-a032-4834-b9ef-5783f0b823d4: 'Project ID' # Project ID
    358db54d-b951-4e0a-b4fa-c43aa2257acc: 'Newsletter Links' # Newsletter Links
    375cd22a-99b6-4667-8ca6-caf2572459ed: Blog # Blog
    504f909d-20af-4a66-b4a5-46c966689b30: 'Resize: width 1000px' # Resize: width 1000px
    633b77bd-edb2-4812-ae43-7d61e39fd8fd: 'Main Footer Links' # Main Footer Links
    645eb55b-61e5-4ed2-bf31-caed18a16ffb: 'Blog Index' # Blog Index
    824f9bd0-21d0-47fd-a48a-b8519da12b29: Quote # Quote
    894e5185-035a-41d1-b272-0b6c1608aabf: 'Side Heading + Text' # Side Heading + Text
    2965e0c7-feb2-4aa2-98d4-de16d458eb30: Categories # Categories
    3660aa23-c5a0-4865-b14d-5bd479e01996: Source # Source
    5593a3e3-ad74-4e68-ad2d-36a6c8f1d95a: 'Project Year Groups' # Project Year Groups
    6848d2a0-5b5f-43f6-a0c7-22707ad5e028: Bio # Bio
    8898a317-df17-4cc9-9475-6376bc29fbd5: 'Newsletter Headline' # Newsletter Headline
    53364b16-adc8-4b34-802f-054c272771c6: 'Projects Index' # Projects Index
    586087db-4dd7-43ba-929b-b3f7cef02ff8: 'Resize: width 0500px' # Resize: width 0500px
    711863fc-e341-4c43-b45b-dc33dc3c9c2b: Homepage # Homepage
    860851bc-5058-4f0d-8f3f-481df7e56099: 'Project Rounds' # Project Rounds
    38533602-ed85-4c63-b7e3-819ae75ac47a: 'Surt – Regular' # Surt – Regular
    65570146-7afc-432e-9890-2cb116aa66ac: Link # Link
    67373325-a234-485a-a635-26dee1e7f325: 'Project Links' # Project Links
    80466913-dc6f-46d5-8013-a55f3a7358da: Sponsors # Sponsors
    a05e468d-5063-4f3a-8ea3-aa240eebc1bf: Newsletter # Newsletter
    a06eff6a-35ff-45b1-9c02-c6ef2f3f948c: 'Project Rounds' # Project Rounds
    a6babdad-fc37-48fb-ac86-088ea4129e1e: Author # Author
    ad1324f8-1337-475f-8516-ab1e13543027: Intro # Intro
    ad6378ef-e24f-4541-9819-1a644a3dd8c4: 'Nav Links' # Nav Links
    af0bbe1c-3613-4775-8a01-965b68d4e56e: English # English
    af427185-4826-4e80-bd57-096797b92f4b: Project # Project
    b44bb4f4-87a6-47c4-ae20-f1594e9a775b: 'Blog Teaser' # Blog Teaser
    b99ee1fe-b466-49ac-8315-43d2af7587e1: Uploads # Uploads
    b629c55a-8642-44db-a823-26783a25058b: Footer # Footer
    bdc78be0-ab3b-4c52-9657-0eaaff1208e9: 'Blog Categories' # Blog Categories
    c0e7400b-5611-4a34-bc52-4cd0edc31e41: Sites # Sites
    c03eff61-59aa-491d-bfa0-db442637813a: Article # Article
    c8c2dcfa-75cb-423f-9565-b550807d0e7e: 'Resize: width 1500px' # Resize: width 1500px
    c85b9b92-e92c-448e-be1b-853494683b99: 'Project Technologies' # Project Technologies
    c86f2a45-9639-4151-93dc-21dce075b6f9: 'Link Group' # Link Group
    c670b800-a19f-4ca2-a056-283204e59d5d: 'Credit / License' # Credit / License
    c63194ff-c47c-4c20-80b1-39bfedfc3b0f: 'Project Topics' # Project Topics
    c4438391-90e5-49b1-93bd-6fcbbd3aed62: Simple # Simple
    cff97bfa-6eb7-473b-97c0-cc3af58c0f64: 'Article ID' # Article ID
    d13f787b-b91b-4821-8104-46e509830347: Avatar # Avatar
    d26ba65b-dbab-4a12-b3e8-1ae7a4a2845d: Quote # Quote
    d5397ea9-1d37-4f12-bf41-46082d130bd8: Image # Image
    d42896d4-04a6-4211-8d97-f265c27a3be1: 'Inclusive Sans – Semibold (Italic)' # Inclusive Sans – Semibold (Italic)
    d99528c4-136b-413c-9799-56fd20edd2c6: Headline # Headline
    da7ab602-1ed1-46b0-9e1c-5ec3a6e60c92: 'Project Teaser' # Project Teaser
    ddc3aedf-983b-4fa7-81eb-69fd761d71af: German # German
    de820dbc-bd7e-4a0f-9554-3d750480d2a4: Projects # Projects
    e30e243f-a8dc-43b7-b826-e4788906231f: Pronouns # Pronouns
    eb089684-4134-4cd9-a60d-4aaac63db8f4: Link # Link
    ed187804-9da6-4b7d-b983-1c751ac7a3ab: 'Tracking Body' # Tracking Body
    eec7038e-53af-4299-bf11-db14e0fbd073: 'Generic Page' # Generic Page
    f2fe1c5e-9903-41ca-a1b9-45815959a6ef: 'Newsletter Link Group' # Newsletter Link Group
    f4a87b3f-ed6d-49ce-8753-05dda85942a6: 'Project Status' # Project Status
    f6ed0d5d-4ab8-418b-801e-b11f6cb309a5: Author # Author
    f81cb75d-92f5-44c4-89bd-673d8c8ee15c: 'Sponsors Headline' # Sponsors Headline
    f81e8821-286e-4e07-86f6-54880a45eafe: 'Project Team Members' # Project Team Members
    f7486108-7a41-4ff3-83e8-34c2b334e19f: Links # Links
    fb0276f2-1481-401a-b813-05bac05b0218: Settings # Settings
    fc819c64-6715-4ac6-8573-d5c49ab5420e: 'Newsletter Text' # Newsletter Text
    fdce3d41-b225-460c-85ea-1908f71ba724: 'Newsletter Secondary Text' # Newsletter Secondary Text
    fe4cc5ff-86a2-4944-a119-aae5f36fa127: 'Surt – Bold' # Surt – Bold
plugins:
  blitz:
    edition: standard
    enabled: true
    licenseKey: E3FLHMS038ASYZCMOT1N7IBT
    schemaVersion: 5.10.0
    settings:
      apiKey: ''
      cacheControlHeader: 'public, s-maxage=31536000, max-age=0'
      cacheControlHeaderExpired: 'public, s-maxage=5, max-age=0'
      cacheDuration: null
      cacheGeneratorSettings:
        __assoc__:
          -
            - concurrency
            - '3'
      cacheGeneratorType: putyourlightson\blitz\drivers\generators\HttpGenerator
      cacheNonHtmlResponses: false
      cachePurgerType: putyourlightson\blitz\drivers\purgers\DummyPurger
      cacheStorageSettings:
        __assoc__:
          -
            - folderPath
            - '@webroot/cache/blitz'
          -
            - compressCachedValues
            - ''
      cacheStorageType: putyourlightson\blitz\drivers\storage\FileStorage
      cachingEnabled: false
      debug: false
      defaultCacheControlHeader: 'no-cache, no-store, must-revalidate'
      deployerType: putyourlightson\blitz\drivers\deployers\DummyDeployer
      detectSsiEnabled: true
      driverJobBatchSize: 100
      driverJobPriority: 100
      esiEnabled: false
      excludedQueryStringParams:
        -
          __assoc__:
            -
              - enabled
              - '1'
            -
              - siteId
              - ''
            -
              - queryStringParam
              - gclid
        -
          __assoc__:
            -
              - enabled
              - '1'
            -
              - siteId
              - ''
            -
              - queryStringParam
              - fbclid
      excludedUriPatterns:
        -
          __assoc__:
            -
              - enabled
              - '1'
            -
              - siteId
              - ''
            -
              - uriPattern
              - knock-knock/who-is-there
        -
          __assoc__:
            -
              - enabled
              - '1'
            -
              - siteId
              - ''
            -
              - uriPattern
              - projects
      generatePagesWithQueryStringParams: true
      hintsEnabled: true
      includedQueryStringParams:
        -
          __assoc__:
            -
              - enabled
              - '1'
            -
              - siteId
              - ''
            -
              - queryStringParam
              - '.*'
      includedUriPatterns:
        1:
          __assoc__:
            -
              - enabled
              - '1'
            -
              - siteId
              - ''
            -
              - uriPattern
              - ''
        2:
          __assoc__:
            -
              - enabled
              - '1'
            -
              - siteId
              - ''
            -
              - uriPattern
              - '.*'
      injectScriptEvent: DOMContentLoaded
      injectScriptPosition: 3
      integrations:
        - putyourlightson\blitz\drivers\integrations\CommerceIntegration
        - putyourlightson\blitz\drivers\integrations\FeedMeIntegration
        - putyourlightson\blitz\drivers\integrations\SeomaticIntegration
      maxRetryAttempts: 10
      maxUriLength: 255
      mutexTimeout: 1
      onlyCacheLowercaseUris: false
      outputComments: true
      purgeAssetImagesWhenChanged: true
      queryStringCaching: 0
      queueJobTtr: 300
      refreshCacheAutomaticallyForGlobals: true
      refreshCacheEnabled: true
      refreshCacheJobPriority: 10
      refreshCacheWhenElementMovedInStructure: true
      refreshCacheWhenElementSavedNotLive: false
      refreshCacheWhenElementSavedUnchanged: false
      refreshMode: 3
      sendPoweredByHeader: true
      ssiEnabled: false
      ssiTagFormat: '<!--#include virtual="{uri}" -->'
      trackElementQueries: true
      trackElements: true
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  feed-me:
    edition: standard
    enabled: true
    schemaVersion: 5.1.1
  knock-knock:
    edition: standard
    enabled: true
    schemaVersion: 1.1.1
  retcon:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  retour:
    edition: standard
    enabled: true
    licenseKey: ZVLSZ9INU5Z8UTHLZAJDQRX6
    schemaVersion: 3.0.12
    settings:
      alwaysStripQueryString: false
      automaticallyTrimStatistics: true
      createUriChangeRedirects: true
      csvColumnDelimiter: ','
      dynamicRedirectDisplayLimit: 100
      enableApiEndpoint: false
      enableStatistics: true
      pluginName: Retour
      preserveQueryString: false
      recordRemoteIp: true
      refreshIntervalSecs: 5
      staticRedirectDisplayLimit: 100
      statisticsRateLimitMs: 3600000
      statsDisplayLimit: 1000
      statsStoredLimit: 1000
      stripQueryStringFromStats: true
      uriChangeRedirectSrcMatch: fullurl
  seomatic:
    edition: standard
    enabled: true
    licenseKey: LXESUA4UFA479FN3T6U5KW1J
    schemaVersion: 3.0.12
    settings:
      addHrefLang: true
      addPaginatedHreflang: true
      addXDefaultHrefLang: true
      alwaysIncludeCanonicalUrls: false
      cpTitlePrefix: '⚙ '
      cspNonce: ''
      cspScriptSrcPolicies:
        -
          __assoc__:
            -
              - policy
              - '''self'''
      devModeCpTitlePrefix: '&#x1f6a7;⚙ '
      devModeTitlePrefix: '&#x1f6a7; '
      displayAnalysisSidebar: true
      displayPreviewSidebar: true
      enableJsonLdEndpoint: false
      enableMetaContainerEndpoint: false
      enableSeoFileLinkEndpoint: false
      environment: live
      excludeNonCanonicalUrls: false
      generatorEnabled: true
      headersEnabled: true
      includeHomepageInBreadcrumbs: true
      lowercaseCanonicalUrl: true
      manuallySetEnvironment: false
      maxDescriptionLength: 155
      maxTitleLength: 70
      metaCacheDuration: 0
      pluginName: SEO
      regenerateSitemapsAutomatically: true
      renderEnabled: true
      separatorChar: '|'
      sidebarDisplayPreviewTypes:
        - google
        - twitter
        - facebook
      siteGroupsSeparate: true
      siteUrlOverride: ''
      sitemapsEnabled: true
      socialMediaPreviewTarget: true
      submitSitemaps: true
      truncateDescriptionTags: true
      truncateTitleTags: true
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: 'Prototype Fund'
  retryDuration: null
  schemaVersion: 5.6.0.2
  timeZone: Europe/Berlin
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
