dateModified: 1739958470
elementSources:
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: '*'
      tableAttributes:
        - section
        - postDate
        - expiryDate
        - link
      type: native
    -
      key: singles
      type: native
    -
      heading: Pages
      type: heading
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: 'section:375cd22a-99b6-4667-8ca6-caf2572459ed' # Blog
      tableAttributes:
        - postDate
        - expiryDate
        - link
      type: native
email:
  fromEmail: $EMAIL_SYSTEM_ADDRESS
  fromName: $EMAIL_SENDER_NAME
  replyToEmail: null
  template: null
  transportSettings:
    command: '/usr/sbin/sendmail -bs'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  uploadsFs:
    hasUrls: true
    name: 'Uploads FS'
    settings:
      path: '@webroot/uploads'
    type: craft\fs\Local
    url: '@web/uploads'
meta:
  __names__:
    0d857c68-7bb1-4ce7-b61f-671446aa8bb3: SEO # SEO
    2b86894c-5b98-44d4-8ed6-88b2c8b5e601: 'Blog Index' # Blog Index
    3bde5cb4-3323-4862-906f-40053b1122bc: 'Main Image' # Main Image
    5cf4a4ac-85fa-4da7-891a-d5d9bf1bf1d4: 'Main Image - Image - Image' # Main Image - Image - Image
    6fa1e10a-d063-4c10-a955-f1b3eda7e7ef: Standard # Standard
    9c0f58c4-4b28-4aca-b80d-3b370bc38f9e: 'Next Reads' # Next Reads
    9cc566a2-cf3f-44d6-82d7-7882f61e176e: 'Main Image - Image - Caption' # Main Image - Image - Caption
    13a0aaca-3bd8-4653-b163-69738ce277c3: Text # Text
    28f95d3d-986f-41ed-b23b-c2f3b747c2eb: Homepage # Homepage
    34dc108f-02bd-42cb-9481-0693c7bc32b4: 'Tracking Head' # Tracking Head
    91a7ad8a-d35b-4738-b71b-a18f899afc5d: 'Resize: width 2000px' # Resize: width 2000px
    375cd22a-99b6-4667-8ca6-caf2572459ed: Blog # Blog
    504f909d-20af-4a66-b4a5-46c966689b30: 'Resize: width 1000px' # Resize: width 1000px
    645eb55b-61e5-4ed2-bf31-caed18a16ffb: 'Blog Index' # Blog Index
    586087db-4dd7-43ba-929b-b3f7cef02ff8: 'Resize: width 0500px' # Resize: width 0500px
    711863fc-e341-4c43-b45b-dc33dc3c9c2b: Homepage # Homepage
    b44bb4f4-87a6-47c4-ae20-f1594e9a775b: 'Blog Teaser' # Blog Teaser
    b99ee1fe-b466-49ac-8315-43d2af7587e1: Uploads # Uploads
    c0e7400b-5611-4a34-bc52-4cd0edc31e41: Sites # Sites
    c03eff61-59aa-491d-bfa0-db442637813a: Article # Article
    c8c2dcfa-75cb-423f-9565-b550807d0e7e: 'Resize: width 1500px' # Resize: width 1500px
    c4438391-90e5-49b1-93bd-6fcbbd3aed62: Simple # Simple
    d5397ea9-1d37-4f12-bf41-46082d130bd8: Image # Image
    ddc3aedf-983b-4fa7-81eb-69fd761d71af: German # German
    ed187804-9da6-4b7d-b983-1c751ac7a3ab: 'Tracking Body' # Tracking Body
    fb0276f2-1481-401a-b813-05bac05b0218: Settings # Settings
plugins:
  blitz:
    edition: standard
    enabled: true
    licenseKey: E3FLHMS038ASYZCMOT1N7IBT
    schemaVersion: 5.9.0
    settings:
      apiKey: ''
      cacheControlHeader: 'public, s-maxage=31536000, max-age=0'
      cacheControlHeaderExpired: 'public, s-maxage=5, max-age=0'
      cacheDuration: null
      cacheElementQueries: true
      cacheElements: true
      cacheGeneratorSettings:
        __assoc__:
          -
            - concurrency
            - '3'
      cacheGeneratorType: putyourlightson\blitz\drivers\generators\HttpGenerator
      cacheNonHtmlResponses: false
      cachePurgerType: putyourlightson\blitz\drivers\purgers\DummyPurger
      cacheStorageSettings:
        __assoc__:
          -
            - folderPath
            - '@webroot/cache/blitz'
          -
            - compressCachedValues
            - ''
      cacheStorageType: putyourlightson\blitz\drivers\storage\FileStorage
      cachingEnabled: false
      debug: false
      defaultCacheControlHeader: 'no-cache, no-store, must-revalidate'
      deployerType: putyourlightson\blitz\drivers\deployers\DummyDeployer
      detectSsiEnabled: true
      driverJobPriority: 100
      esiEnabled: false
      excludedQueryStringParams:
        -
          enabled: true
          queryStringParam: gclid
        -
          enabled: true
          queryStringParam: fbclid
      excludedUriPatterns:
        -
          enabled: true
          uriPattern: knock-knock/who-is-there
      generatePagesWithQueryStringParams: true
      hintsEnabled: true
      includedQueryStringParams:
        -
          enabled: true
          queryStringParam: '.*'
      includedUriPatterns:
        1:
          enabled: true
          uriPattern: ''
        2:
          enabled: true
          uriPattern: '.*'
      injectScriptEvent: DOMContentLoaded
      integrations:
        - putyourlightson\blitz\drivers\integrations\CommerceIntegration
        - putyourlightson\blitz\drivers\integrations\FeedMeIntegration
        - putyourlightson\blitz\drivers\integrations\SeomaticIntegration
      maxRetryAttempts: 10
      maxUriLength: 255
      mutexTimeout: 1
      outputComments: true
      purgeAssetImagesWhenChanged: true
      queryStringCaching: 0
      queueJobTtr: 300
      refreshCacheAutomaticallyForGlobals: true
      refreshCacheJobPriority: 10
      refreshCacheWhenElementMovedInStructure: true
      refreshCacheWhenElementSavedNotLive: false
      refreshCacheWhenElementSavedUnchanged: false
      refreshMode: 3
      sendPoweredByHeader: true
      ssiEnabled: false
      ssiTagFormat: '<!--#include virtual="{uri}" -->'
      trackElementQueries: true
      trackElements: true
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  knock-knock:
    edition: standard
    enabled: true
    schemaVersion: 1.1.1
  retcon:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  retour:
    edition: standard
    enabled: true
    licenseKey: ZVLSZ9INU5Z8UTHLZAJDQRX6
    schemaVersion: 3.0.12
    settings:
      alwaysStripQueryString: false
      automaticallyTrimStatistics: true
      createUriChangeRedirects: true
      csvColumnDelimiter: ','
      dynamicRedirectDisplayLimit: 100
      enableApiEndpoint: false
      enableStatistics: true
      pluginName: Retour
      preserveQueryString: false
      recordRemoteIp: true
      refreshIntervalSecs: 5
      staticRedirectDisplayLimit: 100
      statisticsRateLimitMs: 3600000
      statsDisplayLimit: 1000
      statsStoredLimit: 1000
      stripQueryStringFromStats: true
      uriChangeRedirectSrcMatch: fullurl
  seomatic:
    edition: standard
    enabled: true
    licenseKey: LXESUA4UFA479FN3T6U5KW1J
    schemaVersion: 3.0.12
    settings:
      addHrefLang: true
      addPaginatedHreflang: true
      addXDefaultHrefLang: true
      alwaysIncludeCanonicalUrls: false
      cpTitlePrefix: '⚙ '
      cspNonce: ''
      cspScriptSrcPolicies:
        -
          __assoc__:
            -
              - policy
              - '''self'''
      devModeCpTitlePrefix: '&#x1f6a7;⚙ '
      devModeTitlePrefix: '&#x1f6a7; '
      displayAnalysisSidebar: true
      displayPreviewSidebar: true
      enableJsonLdEndpoint: false
      enableMetaContainerEndpoint: false
      enableSeoFileLinkEndpoint: false
      environment: live
      excludeNonCanonicalUrls: false
      generatorEnabled: true
      headersEnabled: true
      includeHomepageInBreadcrumbs: true
      lowercaseCanonicalUrl: true
      manuallySetEnvironment: false
      maxDescriptionLength: 155
      maxTitleLength: 70
      metaCacheDuration: 0
      pluginName: SEO
      regenerateSitemapsAutomatically: true
      renderEnabled: true
      separatorChar: '|'
      sidebarDisplayPreviewTypes:
        - google
        - twitter
        - facebook
      siteGroupsSeparate: true
      siteUrlOverride: ''
      sitemapsEnabled: true
      socialMediaPreviewTarget: true
      submitSitemaps: true
      truncateDescriptionTags: true
      truncateTitleTags: true
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: 'Prototype Fund'
  retryDuration: null
  schemaVersion: 5.6.0.2
  timeZone: Europe/Berlin
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
