fieldLayouts:
  b9fbfa9e-96a7-4685-a8b0-63debebac98d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-30T21:22:57+00:00'
            elementCondition: null
            fieldUid: e0be08b6-634c-4eed-aa9a-175b6bc828c1 # Enable Announcement Bar
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b0ff21e9-ac0c-4ef5-9bfe-63e4ad7f3d35
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-30T21:30:42+00:00'
            elementCondition: null
            fieldUid: eb089684-4134-4cd9-a60d-4aaac63db8f4 # Link
            handle: announcementLink
            includeInCards: false
            instructions: null
            label: 'Announcement Link'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2eb5ccde-3128-4f67-8117-85e4974c6f5d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 67f9509e-5f56-4042-926e-ec70f741d589
        userCondition: null
handle: announcementBar
name: 'Announcement Bar'
sortOrder: 4
