description: null
handle: editors
name: Editors
permissions:
  - accesscp
  - accesscpwhensystemisoff
  - accessplugin-feed-me
  - accessplugin-retour
  - accessplugin-seomatic
  - accesssitewhensystemisoff
  - 'createentries:375cd22a-99b6-4667-8ca6-caf2572459ed' # Blog
  - 'createentries:4fd1e89f-c494-4e78-ae99-20dbd74e4f9b' # Publications
  - 'createentries:539be7e4-0b10-472e-b4de-ec2fbea58c78' # Trends
  - 'createentries:6e040108-27cc-4a4a-bca9-c5e3ab1bdc04' # Generic Pages
  - 'createentries:9b03faaf-18e7-4df7-b87c-282d1ead8ea3' # Jury
  - 'createentries:a22a67ef-b1de-4d1d-b922-5ea14b3e8e1c' # Team
  - 'createentries:a6babdad-fc37-48fb-ac86-088ea4129e1e' # Authors
  - 'createentries:a805834b-57ba-4e15-8082-a5bf2c23d495' # FAQs
  - 'createentries:b8ee6536-12a5-4426-b64d-b04a622f6dbf' # Link Lists
  - 'createentries:de820dbc-bd7e-4a0f-9554-3d750480d2a4' # Projects
  - 'createentries:ed498341-57c0-4a5d-bedd-9728b250d140' # CTA Banners
  - 'createentries:f1478917-bc75-4118-b7d9-7cd5fdae8872' # Timelines
  - 'createfolders:b99ee1fe-b466-49ac-8315-43d2af7587e1' # Uploads
  - 'deleteassets:b99ee1fe-b466-49ac-8315-43d2af7587e1' # Uploads
  - 'deletecategories:5593a3e3-ad74-4e68-ad2d-36a6c8f1d95a' # Project Year Groups
  - 'deletecategories:8d8e3436-a20e-4222-a530-d52fa736ae4d' # Project Technologies
  - 'deletecategories:a06eff6a-35ff-45b1-9c02-c6ef2f3f948c' # Project Rounds
  - 'deletecategories:bdc78be0-ab3b-4c52-9657-0eaaff1208e9' # Blog Categories
  - 'deletecategories:c63194ff-c47c-4c20-80b1-39bfedfc3b0f' # Project Topics
  - 'deleteentries:375cd22a-99b6-4667-8ca6-caf2572459ed' # Blog
  - 'deleteentries:4fd1e89f-c494-4e78-ae99-20dbd74e4f9b' # Publications
  - 'deleteentries:539be7e4-0b10-472e-b4de-ec2fbea58c78' # Trends
  - 'deleteentries:6e040108-27cc-4a4a-bca9-c5e3ab1bdc04' # Generic Pages
  - 'deleteentries:9b03faaf-18e7-4df7-b87c-282d1ead8ea3' # Jury
  - 'deleteentries:a22a67ef-b1de-4d1d-b922-5ea14b3e8e1c' # Team
  - 'deleteentries:a6babdad-fc37-48fb-ac86-088ea4129e1e' # Authors
  - 'deleteentries:a805834b-57ba-4e15-8082-a5bf2c23d495' # FAQs
  - 'deleteentries:b8ee6536-12a5-4426-b64d-b04a622f6dbf' # Link Lists
  - 'deleteentries:de820dbc-bd7e-4a0f-9554-3d750480d2a4' # Projects
  - 'deleteentries:ed498341-57c0-4a5d-bedd-9728b250d140' # CTA Banners
  - 'deleteentries:f1478917-bc75-4118-b7d9-7cd5fdae8872' # Timelines
  - 'deletepeerassets:b99ee1fe-b466-49ac-8315-43d2af7587e1' # Uploads
  - 'deletepeercategorydrafts:5593a3e3-ad74-4e68-ad2d-36a6c8f1d95a' # Project Year Groups
  - 'deletepeercategorydrafts:8d8e3436-a20e-4222-a530-d52fa736ae4d' # Project Technologies
  - 'deletepeercategorydrafts:a06eff6a-35ff-45b1-9c02-c6ef2f3f948c' # Project Rounds
  - 'deletepeercategorydrafts:bdc78be0-ab3b-4c52-9657-0eaaff1208e9' # Blog Categories
  - 'deletepeercategorydrafts:c63194ff-c47c-4c20-80b1-39bfedfc3b0f' # Project Topics
  - 'deletepeerentries:375cd22a-99b6-4667-8ca6-caf2572459ed' # Blog
  - 'deletepeerentries:4fd1e89f-c494-4e78-ae99-20dbd74e4f9b' # Publications
  - 'deletepeerentries:539be7e4-0b10-472e-b4de-ec2fbea58c78' # Trends
  - 'deletepeerentries:6e040108-27cc-4a4a-bca9-c5e3ab1bdc04' # Generic Pages
  - 'deletepeerentries:9b03faaf-18e7-4df7-b87c-282d1ead8ea3' # Jury
  - 'deletepeerentries:a22a67ef-b1de-4d1d-b922-5ea14b3e8e1c' # Team
  - 'deletepeerentries:a6babdad-fc37-48fb-ac86-088ea4129e1e' # Authors
  - 'deletepeerentries:a805834b-57ba-4e15-8082-a5bf2c23d495' # FAQs
  - 'deletepeerentries:b8ee6536-12a5-4426-b64d-b04a622f6dbf' # Link Lists
  - 'deletepeerentries:de820dbc-bd7e-4a0f-9554-3d750480d2a4' # Projects
  - 'deletepeerentries:ed498341-57c0-4a5d-bedd-9728b250d140' # CTA Banners
  - 'deletepeerentries:f1478917-bc75-4118-b7d9-7cd5fdae8872' # Timelines
  - 'deletepeerentrydrafts:1f4132a7-2573-4ef2-9585-5323907ea4b4' # Newsletter
  - 'deletepeerentrydrafts:28f95d3d-986f-41ed-b23b-c2f3b747c2eb' # Homepage
  - 'deletepeerentrydrafts:29d80674-cc17-4976-ad67-b3f611a07dc2' # Events Index
  - 'deletepeerentrydrafts:375cd22a-99b6-4667-8ca6-caf2572459ed' # Blog
  - 'deletepeerentrydrafts:4fd1e89f-c494-4e78-ae99-20dbd74e4f9b' # Publications
  - 'deletepeerentrydrafts:53364b16-adc8-4b34-802f-054c272771c6' # Projects Index
  - 'deletepeerentrydrafts:539be7e4-0b10-472e-b4de-ec2fbea58c78' # Trends
  - 'deletepeerentrydrafts:546a2098-ec0e-4c83-aafc-66cdc354f32f' # Trends Index
  - 'deletepeerentrydrafts:645eb55b-61e5-4ed2-bf31-caed18a16ffb' # Blog Index
  - 'deletepeerentrydrafts:6e040108-27cc-4a4a-bca9-c5e3ab1bdc04' # Generic Pages
  - 'deletepeerentrydrafts:9b03faaf-18e7-4df7-b87c-282d1ead8ea3' # Jury
  - 'deletepeerentrydrafts:a22a67ef-b1de-4d1d-b922-5ea14b3e8e1c' # Team
  - 'deletepeerentrydrafts:a6babdad-fc37-48fb-ac86-088ea4129e1e' # Authors
  - 'deletepeerentrydrafts:a805834b-57ba-4e15-8082-a5bf2c23d495' # FAQs
  - 'deletepeerentrydrafts:b8ee6536-12a5-4426-b64d-b04a622f6dbf' # Link Lists
  - 'deletepeerentrydrafts:db229da2-7471-4db0-a3ec-697da49531d1'
  - 'deletepeerentrydrafts:de820dbc-bd7e-4a0f-9554-3d750480d2a4' # Projects
  - 'deletepeerentrydrafts:ed498341-57c0-4a5d-bedd-9728b250d140' # CTA Banners
  - 'deletepeerentrydrafts:f1478917-bc75-4118-b7d9-7cd5fdae8872' # Timelines
  - 'editglobalset:137c86ac-e143-4792-b936-38c41302eccd' # Fonts
  - 'editglobalset:4b6ba907-43f2-494b-9816-24894f8de0da' # Newsletter
  - 'editglobalset:4e97404d-0992-4280-b87e-903b4fc471c5' # Navigation
  - 'editglobalset:b629c55a-8642-44db-a823-26783a25058b' # Footer
  - 'editglobalset:fb0276f2-1481-401a-b813-05bac05b0218' # Settings
  - 'editimages:b99ee1fe-b466-49ac-8315-43d2af7587e1' # Uploads
  - 'editpeerimages:b99ee1fe-b466-49ac-8315-43d2af7587e1' # Uploads
  - 'editsite:af0bbe1c-3613-4775-8a01-965b68d4e56e' # English
  - 'editsite:ddc3aedf-983b-4fa7-81eb-69fd761d71af' # German
  - performupdates
  - 'replacefiles:b99ee1fe-b466-49ac-8315-43d2af7587e1' # Uploads
  - 'replacepeerfiles:b99ee1fe-b466-49ac-8315-43d2af7587e1' # Uploads
  - 'retour:dashboard'
  - 'retour:redirects'
  - 'retour:settings'
  - 'retour:shortlinks'
  - 'saveassets:b99ee1fe-b466-49ac-8315-43d2af7587e1' # Uploads
  - 'savecategories:5593a3e3-ad74-4e68-ad2d-36a6c8f1d95a' # Project Year Groups
  - 'savecategories:8d8e3436-a20e-4222-a530-d52fa736ae4d' # Project Technologies
  - 'savecategories:a06eff6a-35ff-45b1-9c02-c6ef2f3f948c' # Project Rounds
  - 'savecategories:bdc78be0-ab3b-4c52-9657-0eaaff1208e9' # Blog Categories
  - 'savecategories:c63194ff-c47c-4c20-80b1-39bfedfc3b0f' # Project Topics
  - 'saveentries:1f4132a7-2573-4ef2-9585-5323907ea4b4' # Newsletter
  - 'saveentries:28f95d3d-986f-41ed-b23b-c2f3b747c2eb' # Homepage
  - 'saveentries:29d80674-cc17-4976-ad67-b3f611a07dc2' # Events Index
  - 'saveentries:375cd22a-99b6-4667-8ca6-caf2572459ed' # Blog
  - 'saveentries:4fd1e89f-c494-4e78-ae99-20dbd74e4f9b' # Publications
  - 'saveentries:53364b16-adc8-4b34-802f-054c272771c6' # Projects Index
  - 'saveentries:539be7e4-0b10-472e-b4de-ec2fbea58c78' # Trends
  - 'saveentries:546a2098-ec0e-4c83-aafc-66cdc354f32f' # Trends Index
  - 'saveentries:645eb55b-61e5-4ed2-bf31-caed18a16ffb' # Blog Index
  - 'saveentries:6e040108-27cc-4a4a-bca9-c5e3ab1bdc04' # Generic Pages
  - 'saveentries:9b03faaf-18e7-4df7-b87c-282d1ead8ea3' # Jury
  - 'saveentries:a22a67ef-b1de-4d1d-b922-5ea14b3e8e1c' # Team
  - 'saveentries:a6babdad-fc37-48fb-ac86-088ea4129e1e' # Authors
  - 'saveentries:a805834b-57ba-4e15-8082-a5bf2c23d495' # FAQs
  - 'saveentries:b8ee6536-12a5-4426-b64d-b04a622f6dbf' # Link Lists
  - 'saveentries:db229da2-7471-4db0-a3ec-697da49531d1'
  - 'saveentries:de820dbc-bd7e-4a0f-9554-3d750480d2a4' # Projects
  - 'saveentries:ed498341-57c0-4a5d-bedd-9728b250d140' # CTA Banners
  - 'saveentries:f1478917-bc75-4118-b7d9-7cd5fdae8872' # Timelines
  - 'savepeerassets:b99ee1fe-b466-49ac-8315-43d2af7587e1' # Uploads
  - 'savepeercategorydrafts:5593a3e3-ad74-4e68-ad2d-36a6c8f1d95a' # Project Year Groups
  - 'savepeercategorydrafts:8d8e3436-a20e-4222-a530-d52fa736ae4d' # Project Technologies
  - 'savepeercategorydrafts:a06eff6a-35ff-45b1-9c02-c6ef2f3f948c' # Project Rounds
  - 'savepeercategorydrafts:bdc78be0-ab3b-4c52-9657-0eaaff1208e9' # Blog Categories
  - 'savepeercategorydrafts:c63194ff-c47c-4c20-80b1-39bfedfc3b0f' # Project Topics
  - 'savepeerentries:375cd22a-99b6-4667-8ca6-caf2572459ed' # Blog
  - 'savepeerentries:4fd1e89f-c494-4e78-ae99-20dbd74e4f9b' # Publications
  - 'savepeerentries:539be7e4-0b10-472e-b4de-ec2fbea58c78' # Trends
  - 'savepeerentries:6e040108-27cc-4a4a-bca9-c5e3ab1bdc04' # Generic Pages
  - 'savepeerentries:9b03faaf-18e7-4df7-b87c-282d1ead8ea3' # Jury
  - 'savepeerentries:a22a67ef-b1de-4d1d-b922-5ea14b3e8e1c' # Team
  - 'savepeerentries:a6babdad-fc37-48fb-ac86-088ea4129e1e' # Authors
  - 'savepeerentries:a805834b-57ba-4e15-8082-a5bf2c23d495' # FAQs
  - 'savepeerentries:b8ee6536-12a5-4426-b64d-b04a622f6dbf' # Link Lists
  - 'savepeerentries:de820dbc-bd7e-4a0f-9554-3d750480d2a4' # Projects
  - 'savepeerentries:ed498341-57c0-4a5d-bedd-9728b250d140' # CTA Banners
  - 'savepeerentries:f1478917-bc75-4118-b7d9-7cd5fdae8872' # Timelines
  - 'savepeerentrydrafts:1f4132a7-2573-4ef2-9585-5323907ea4b4' # Newsletter
  - 'savepeerentrydrafts:28f95d3d-986f-41ed-b23b-c2f3b747c2eb' # Homepage
  - 'savepeerentrydrafts:29d80674-cc17-4976-ad67-b3f611a07dc2' # Events Index
  - 'savepeerentrydrafts:375cd22a-99b6-4667-8ca6-caf2572459ed' # Blog
  - 'savepeerentrydrafts:4fd1e89f-c494-4e78-ae99-20dbd74e4f9b' # Publications
  - 'savepeerentrydrafts:53364b16-adc8-4b34-802f-054c272771c6' # Projects Index
  - 'savepeerentrydrafts:539be7e4-0b10-472e-b4de-ec2fbea58c78' # Trends
  - 'savepeerentrydrafts:546a2098-ec0e-4c83-aafc-66cdc354f32f' # Trends Index
  - 'savepeerentrydrafts:645eb55b-61e5-4ed2-bf31-caed18a16ffb' # Blog Index
  - 'savepeerentrydrafts:6e040108-27cc-4a4a-bca9-c5e3ab1bdc04' # Generic Pages
  - 'savepeerentrydrafts:9b03faaf-18e7-4df7-b87c-282d1ead8ea3' # Jury
  - 'savepeerentrydrafts:a22a67ef-b1de-4d1d-b922-5ea14b3e8e1c' # Team
  - 'savepeerentrydrafts:a6babdad-fc37-48fb-ac86-088ea4129e1e' # Authors
  - 'savepeerentrydrafts:a805834b-57ba-4e15-8082-a5bf2c23d495' # FAQs
  - 'savepeerentrydrafts:b8ee6536-12a5-4426-b64d-b04a622f6dbf' # Link Lists
  - 'savepeerentrydrafts:db229da2-7471-4db0-a3ec-697da49531d1'
  - 'savepeerentrydrafts:de820dbc-bd7e-4a0f-9554-3d750480d2a4' # Projects
  - 'savepeerentrydrafts:ed498341-57c0-4a5d-bedd-9728b250d140' # CTA Banners
  - 'savepeerentrydrafts:f1478917-bc75-4118-b7d9-7cd5fdae8872' # Timelines
  - 'seomatic:content-meta'
  - 'seomatic:content-meta:facebook'
  - 'seomatic:content-meta:general'
  - 'seomatic:content-meta:sitemap'
  - 'seomatic:content-meta:twitter'
  - 'seomatic:dashboard'
  - 'seomatic:global-meta'
  - 'seomatic:global-meta:ads'
  - 'seomatic:global-meta:facebook'
  - 'seomatic:global-meta:general'
  - 'seomatic:global-meta:humans'
  - 'seomatic:global-meta:robots'
  - 'seomatic:global-meta:security'
  - 'seomatic:global-meta:twitter'
  - 'seomatic:plugin-settings'
  - 'seomatic:site-settings'
  - 'seomatic:site-settings:creator'
  - 'seomatic:site-settings:identity'
  - 'seomatic:site-settings:miscellaneous'
  - 'seomatic:site-settings:sitemap'
  - 'seomatic:site-settings:social'
  - 'seomatic:tracking-scripts'
  - 'seomatic:tracking-scripts:facebookpixel'
  - 'seomatic:tracking-scripts:fathom'
  - 'seomatic:tracking-scripts:googleanalytics'
  - 'seomatic:tracking-scripts:googletagmanager'
  - 'seomatic:tracking-scripts:gtag'
  - 'seomatic:tracking-scripts:hubspot'
  - 'seomatic:tracking-scripts:linkedininsight'
  - 'seomatic:tracking-scripts:matomo'
  - 'seomatic:tracking-scripts:pinteresttag'
  - 'seomatic:tracking-scripts:plausible'
  - 'viewassets:b99ee1fe-b466-49ac-8315-43d2af7587e1' # Uploads
  - 'viewcategories:5593a3e3-ad74-4e68-ad2d-36a6c8f1d95a' # Project Year Groups
  - 'viewcategories:8d8e3436-a20e-4222-a530-d52fa736ae4d' # Project Technologies
  - 'viewcategories:a06eff6a-35ff-45b1-9c02-c6ef2f3f948c' # Project Rounds
  - 'viewcategories:bdc78be0-ab3b-4c52-9657-0eaaff1208e9' # Blog Categories
  - 'viewcategories:c63194ff-c47c-4c20-80b1-39bfedfc3b0f' # Project Topics
  - 'viewentries:1f4132a7-2573-4ef2-9585-5323907ea4b4' # Newsletter
  - 'viewentries:28f95d3d-986f-41ed-b23b-c2f3b747c2eb' # Homepage
  - 'viewentries:29d80674-cc17-4976-ad67-b3f611a07dc2' # Events Index
  - 'viewentries:375cd22a-99b6-4667-8ca6-caf2572459ed' # Blog
  - 'viewentries:4fd1e89f-c494-4e78-ae99-20dbd74e4f9b' # Publications
  - 'viewentries:53364b16-adc8-4b34-802f-054c272771c6' # Projects Index
  - 'viewentries:539be7e4-0b10-472e-b4de-ec2fbea58c78' # Trends
  - 'viewentries:546a2098-ec0e-4c83-aafc-66cdc354f32f' # Trends Index
  - 'viewentries:645eb55b-61e5-4ed2-bf31-caed18a16ffb' # Blog Index
  - 'viewentries:6e040108-27cc-4a4a-bca9-c5e3ab1bdc04' # Generic Pages
  - 'viewentries:9b03faaf-18e7-4df7-b87c-282d1ead8ea3' # Jury
  - 'viewentries:a22a67ef-b1de-4d1d-b922-5ea14b3e8e1c' # Team
  - 'viewentries:a6babdad-fc37-48fb-ac86-088ea4129e1e' # Authors
  - 'viewentries:a805834b-57ba-4e15-8082-a5bf2c23d495' # FAQs
  - 'viewentries:b8ee6536-12a5-4426-b64d-b04a622f6dbf' # Link Lists
  - 'viewentries:db229da2-7471-4db0-a3ec-697da49531d1'
  - 'viewentries:de820dbc-bd7e-4a0f-9554-3d750480d2a4' # Projects
  - 'viewentries:ed498341-57c0-4a5d-bedd-9728b250d140' # CTA Banners
  - 'viewentries:f1478917-bc75-4118-b7d9-7cd5fdae8872' # Timelines
  - 'viewpeerassets:b99ee1fe-b466-49ac-8315-43d2af7587e1' # Uploads
  - 'viewpeercategorydrafts:5593a3e3-ad74-4e68-ad2d-36a6c8f1d95a' # Project Year Groups
  - 'viewpeercategorydrafts:8d8e3436-a20e-4222-a530-d52fa736ae4d' # Project Technologies
  - 'viewpeercategorydrafts:a06eff6a-35ff-45b1-9c02-c6ef2f3f948c' # Project Rounds
  - 'viewpeercategorydrafts:bdc78be0-ab3b-4c52-9657-0eaaff1208e9' # Blog Categories
  - 'viewpeercategorydrafts:c63194ff-c47c-4c20-80b1-39bfedfc3b0f' # Project Topics
  - 'viewpeerentries:375cd22a-99b6-4667-8ca6-caf2572459ed' # Blog
  - 'viewpeerentries:4fd1e89f-c494-4e78-ae99-20dbd74e4f9b' # Publications
  - 'viewpeerentries:539be7e4-0b10-472e-b4de-ec2fbea58c78' # Trends
  - 'viewpeerentries:6e040108-27cc-4a4a-bca9-c5e3ab1bdc04' # Generic Pages
  - 'viewpeerentries:9b03faaf-18e7-4df7-b87c-282d1ead8ea3' # Jury
  - 'viewpeerentries:a22a67ef-b1de-4d1d-b922-5ea14b3e8e1c' # Team
  - 'viewpeerentries:a6babdad-fc37-48fb-ac86-088ea4129e1e' # Authors
  - 'viewpeerentries:a805834b-57ba-4e15-8082-a5bf2c23d495' # FAQs
  - 'viewpeerentries:b8ee6536-12a5-4426-b64d-b04a622f6dbf' # Link Lists
  - 'viewpeerentries:de820dbc-bd7e-4a0f-9554-3d750480d2a4' # Projects
  - 'viewpeerentries:ed498341-57c0-4a5d-bedd-9728b250d140' # CTA Banners
  - 'viewpeerentries:f1478917-bc75-4118-b7d9-7cd5fdae8872' # Timelines
  - 'viewpeerentrydrafts:1f4132a7-2573-4ef2-9585-5323907ea4b4' # Newsletter
  - 'viewpeerentrydrafts:28f95d3d-986f-41ed-b23b-c2f3b747c2eb' # Homepage
  - 'viewpeerentrydrafts:29d80674-cc17-4976-ad67-b3f611a07dc2' # Events Index
  - 'viewpeerentrydrafts:375cd22a-99b6-4667-8ca6-caf2572459ed' # Blog
  - 'viewpeerentrydrafts:4fd1e89f-c494-4e78-ae99-20dbd74e4f9b' # Publications
  - 'viewpeerentrydrafts:53364b16-adc8-4b34-802f-054c272771c6' # Projects Index
  - 'viewpeerentrydrafts:539be7e4-0b10-472e-b4de-ec2fbea58c78' # Trends
  - 'viewpeerentrydrafts:546a2098-ec0e-4c83-aafc-66cdc354f32f' # Trends Index
  - 'viewpeerentrydrafts:645eb55b-61e5-4ed2-bf31-caed18a16ffb' # Blog Index
  - 'viewpeerentrydrafts:6e040108-27cc-4a4a-bca9-c5e3ab1bdc04' # Generic Pages
  - 'viewpeerentrydrafts:9b03faaf-18e7-4df7-b87c-282d1ead8ea3' # Jury
  - 'viewpeerentrydrafts:a22a67ef-b1de-4d1d-b922-5ea14b3e8e1c' # Team
  - 'viewpeerentrydrafts:a6babdad-fc37-48fb-ac86-088ea4129e1e' # Authors
  - 'viewpeerentrydrafts:a805834b-57ba-4e15-8082-a5bf2c23d495' # FAQs
  - 'viewpeerentrydrafts:b8ee6536-12a5-4426-b64d-b04a622f6dbf' # Link Lists
  - 'viewpeerentrydrafts:db229da2-7471-4db0-a3ec-697da49531d1'
  - 'viewpeerentrydrafts:de820dbc-bd7e-4a0f-9554-3d750480d2a4' # Projects
  - 'viewpeerentrydrafts:ed498341-57c0-4a5d-bedd-9728b250d140' # CTA Banners
  - 'viewpeerentrydrafts:f1478917-bc75-4118-b7d9-7cd5fdae8872' # Timelines
