defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 994e9c1d-7448-4401-bdc6-2657748b1205 # Application
handle: application
maxAuthors: 1
name: Application
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  af0bbe1c-3613-4775-8a01-965b68d4e56e: # English
    enabledByDefault: true
    hasUrls: true
    template: application/index.twig
    uriFormat: application
  ddc3aedf-983b-4fa7-81eb-69fd761d71af: # German
    enabledByDefault: true
    hasUrls: true
    template: application/index.twig
    uriFormat: bewerbung
type: single
