defaultPlacement: end
enableVersioning: true
entryTypes:
  - c03eff61-59aa-491d-bfa0-db442637813a # Article
handle: blog
maxAuthors: 1
name: Blog
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  ddc3aedf-983b-4fa7-81eb-69fd761d71af: # German
    enabledByDefault: true
    hasUrls: true
    template: blog/_entry
    uriFormat: 'blog/{slug}'
type: channel
