defaultPlacement: end
enableVersioning: true
entryTypes:
  - 2b86894c-5b98-44d4-8ed6-88b2c8b5e601 # Blog Index
handle: blogIndex
maxAuthors: 1
name: 'Blog Index'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  ddc3aedf-983b-4fa7-81eb-69fd761d71af: # Primary Site
    enabledByDefault: true
    hasUrls: true
    template: blog/index
    uriFormat: blog
type: single
