defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: ac14f0ca-4155-4f2f-ad58-f2648062e062 # Event
handle: events
maxAuthors: 1
name: Events
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  af0bbe1c-3613-4775-8a01-965b68d4e56e: # English
    enabledByDefault: true
    hasUrls: true
    template: events/_entry.twig
    uriFormat: 'events/{slug}'
  ddc3aedf-983b-4fa7-81eb-69fd761d71af: # German
    enabledByDefault: true
    hasUrls: true
    template: events/_entry.twig
    uriFormat: 'events/{slug}'
type: channel
