defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 1a0ed17a-7208-4b7e-894f-64506d5432d6 # Events Index
handle: eventsIndex
maxAuthors: 1
name: 'Events Index'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  af0bbe1c-3613-4775-8a01-965b68d4e56e: # English
    enabledByDefault: true
    hasUrls: true
    template: events/index
    uriFormat: events
  ddc3aedf-983b-4fa7-81eb-69fd761d71af: # German
    enabledByDefault: true
    hasUrls: true
    template: events/index
    uriFormat: events
type: single
