defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: eec7038e-53af-4299-bf11-db14e0fbd073 # Generic Page
handle: genericPages
maxAuthors: 1
name: 'Generic Pages'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  af0bbe1c-3613-4775-8a01-965b68d4e56e: # English
    enabledByDefault: true
    hasUrls: true
    template: generic/_entry
    uriFormat: '{parent.uri ? parent.uri ~ ''/'' : ''''}{slug}'
  ddc3aedf-983b-4fa7-81eb-69fd761d71af: # German
    enabledByDefault: true
    hasUrls: true
    template: generic/_entry
    uriFormat: '{parent.uri ? parent.uri ~ ''/'' : ''''}{slug}'
structure:
  maxLevels: 2
  uid: 11596e27-9b13-4068-b549-95fad3c2585f
type: structure
