defaultPlacement: end
enableVersioning: true
entryTypes:
  - 711863fc-e341-4c43-b45b-dc33dc3c9c2b # Homepage
handle: homepage
maxAuthors: 1
name: Homepage
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  ddc3aedf-983b-4fa7-81eb-69fd761d71af: # German
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
