defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 2b8e8081-de20-479d-a37d-362dded4c944 # Juror
handle: jury
maxAuthors: 1
name: Jury
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  af0bbe1c-3613-4775-8a01-965b68d4e56e: # English
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  ddc3aedf-983b-4fa7-81eb-69fd761d71af: # German
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
