defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 16d093d2-5427-4466-a013-a3620b62ef69 # Newsletter
handle: newsletter
maxAuthors: 1
name: Newsletter
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  af0bbe1c-3613-4775-8a01-965b68d4e56e: # English
    enabledByDefault: true
    hasUrls: true
    template: newsletter/index.twig
    uriFormat: newsletter
  ddc3aedf-983b-4fa7-81eb-69fd761d71af: # German
    enabledByDefault: true
    hasUrls: true
    template: newsletter/index.twig
    uriFormat: newsletter
type: single
