defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 7eb26dd5-1c10-45d1-a16b-85a148e4bf8a # Projects Index
handle: projectsIndex
maxAuthors: 1
name: 'Projects Index'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  af0bbe1c-3613-4775-8a01-965b68d4e56e: # English
    enabledByDefault: true
    hasUrls: true
    template: projects/index.twig
    uriFormat: projects
  ddc3aedf-983b-4fa7-81eb-69fd761d71af: # German
    enabledByDefault: true
    hasUrls: true
    template: projects/index.twig
    uriFormat: projects
type: single
