defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: e52cab12-65a2-4958-badf-d0b2f39913d0 # Timeline
handle: timelines
maxAuthors: 1
name: Timelines
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  af0bbe1c-3613-4775-8a01-965b68d4e56e: # English
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  ddc3aedf-983b-4fa7-81eb-69fd761d71af: # German
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
