defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 77212406-e8de-43e1-a55b-7e66555059d5 # Trend
handle: trends
maxAuthors: 1
name: Trends
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  af0bbe1c-3613-4775-8a01-965b68d4e56e: # English
    enabledByDefault: true
    hasUrls: true
    template: trends/_entry.twig
    uriFormat: 'trend-research/{slug}'
  ddc3aedf-983b-4fa7-81eb-69fd761d71af: # German
    enabledByDefault: true
    hasUrls: true
    template: trends/_entry.twig
    uriFormat: 'trendforschung/{slug}'
type: channel
