defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 8042936f-727d-4d5e-a1ae-0db7cabde8a8 # Year Groups Index
handle: yearGroupsIndex
maxAuthors: 1
name: 'Year Groups Index'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  af0bbe1c-3613-4775-8a01-965b68d4e56e: # English
    enabledByDefault: true
    hasUrls: true
    template: year-groups/index.twig
    uriFormat: classes
  ddc3aedf-983b-4fa7-81eb-69fd761d71af: # German
    enabledByDefault: true
    hasUrls: true
    template: year-groups/index.twig
    uriFormat: jahrgaenge
type: single
